
<div id="admin" class="page">
    <!-- Top Nav -->
    <h2 class="with-nav">
        <div class="nav-scroller">
            <span id="mode-editor">Editor</span>
            <a href="javascript:;" id="mode-preview">Preview</a>
        </div>
    </h2>

    <!-- Edit form -->
    <form id="edit-form" class="clearfix" action="<?php echo $this->url->get( 'admin/pages/save' ); ?>" method="post">
        <!-- Code Editor -->
        <div class="margin-bottom-40">

        </div><!-- /code editor -->
    </form><!-- /edit form -->

    <!-- Preview Mode -->
    <div class="margin-bottom-40" id="preview" style="display:none;">

    </div>
</div>
