
<div id="admin" class="page editor">
    <!-- Top Nav -->
    <h2 class="with-nav margin-bottom-0">
        <div class="nav-scroller">
            <span id="mode-editor">Editor</span>
            <a href="javascript:;" id="mode-preview">Preview</a>
        </div>
    </h2>

    <!-- Edit form -->
    <form id="editor-form" class="clearfix" action="<?php echo $this->url->get( 'admin/pages/save' ); ?>" method="post">
        <!-- Code Editor -->
        <div id="editor"><?php echo htmlspecialchars( $page->content ); ?></div>
        <input type="hidden" name="name" value="<?php echo $page->name; ?>" />
        <input type="hidden" name="content" value="" id="editor-content" />
    </form><!-- /edit form -->

    <!-- Preview Mode -->
    <div class="margin-bottom-40" id="preview" style="display:none;"></div>

    <!-- Load the Ace Editor -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.0/ace.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.0/mode-html.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.0/theme-twilight.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.0/theme-chrome.js" type="text/javascript"></script>
</div>
