<div id="admin" class="page">
    <!-- Users table -->
    <?php
    $this->partial(
        'partials/admin/nav',
        [ 'adminNavPage' => 'pages' ]); ?>
    <table id="pages" cellspacing="0">
        <thead>
            <tr>
                <th class="lefted-text">Page Name</th>
                <th class="lefted-text">Owner</th>
                <th class="lefted-text">Last Modified</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        <?php
        foreach ( $pages as $page ): ?>
            <tr>
                <td>
                    <a href="<?php echo $this->url->get( 'admin/pages/edit/'. $page->name ); ?>"><?php echo $page->label; ?></a>
                </td>
                <td><?php echo $page->getOwner()->name; ?></td>
                <td><?php echo date_str( $page->modified_at, DATE_MONTH_TIME_YEAR, FALSE, TRUE ); ?></td>
                <td class="centered-text">
                    <a href="<?php echo $this->url->get( 'admin/pages/edit/'. $page->name ); ?>">Edit</a>
                </td>
            </tr>

        <?php
        endforeach; ?>
        </tbody>
    </table>
</div>
