<div id="admin" class="page">
    <!-- Users table -->
    <?php
    $this->partial(
        'partials/admin/nav',
        [ 'adminNavPage' => 'pages' ]); ?>
    <table id="pages" cellspacing="0">
        <thead>
            <tr>
                <th class="lefted-text">Page Name</th>
                <th class="lefted-text">Owner</th>
                <th class="lefted-text">Last Modified</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        <?php
        foreach ( $pages as $index => $label ): ?>
            <tr>
                <td>
                    <a href="<?php echo $this->url->get( 'admin/pages/edit/'. $index ); ?>"><?php echo $label; ?></a>
                </td>
                <td></td>
                <td></td>
                <td class="centered-text">
                    <a href="<?php echo $this->url->get( 'admin/pages/edit/'. $index ); ?>">Edit</a>
                </td>
            </tr>

        <?php
        endforeach; ?>
        </tbody>
    </table>
</div>
