<?php   $count = count( $events );
        if ( $count ):
            $i = 0;
            foreach ( $events as $event ):
                $eventDate = strtotime( $event->event_date );
                $imagePath = $event->getImage()->getPath( 310 );
                if ( ! valid( $imagePath, STRING ) ):
                    $imagePath = $this->url->getStatic( 'img/heptagon_placeholder.png' );
                endif;
                // open a new row div on 0, 3, 6,... but don't open one
                // if there are no more items left
                if ( $i % 3 == 0 ): ?>
<div class="row clearfix">
<?php           endif; ?>

    <div class="archive-event position-relative">
        <a class="blocked banner-wrap margin-bottom-15" href="<?php echo $event->getPath(); ?>"
            style="background-image: url( '<?php echo $imagePath; ?>' );"></a>
        <h2 class="font-mono uppercase margin-bottom-10 break-word">
            <a href="<?php echo $event->getPath(); ?>" class="color-333 hover-underline"><?php echo $event->title; ?></a>
        </h2>

<?php           if ( ! isset( $hideDate ) || $hideDate == FALSE ): ?>
        <div class="date fontsize-15 color-999">
            <?php echo date( DATE_DAY_NAME_YEAR, $eventDate ); ?>
<?php               if ( valid( $event->event_date_end, DATE ) ): ?>
            &mdash;
            <?php echo date( DATE_DAY_NAME_YEAR, strtotime( $event->event_date_end ) ); ?>
<?php               endif; ?>
        </div>
<?php               if ( valid( $event->event_time, STRING ) ): ?>
        <div class="date fontsize-15 color-999 margin-top-5">
            <span class="margin-left-1"><?php echo $event->getShortTime(); ?></span>
        </div>
<?php               endif;
                endif; ?>

        <div class="margin-top-10 padding-bottom-10 lineheight-24">
            <?php echo ( strlen( $event->excerpt ) )
                    ? $event->excerpt
                    : substr(
                        strip_tags( $event->getHtmlBody() ),
                        0,
                        120 ); ?>
        </div>
    </div>

<?php           // end the row if we're either out of elements, or
                // we're 2, 5, 8,...
                if ( $i % 3 == 2 || $i + 1 >= $count ): ?>
</div><!-- /row -->
<?php           endif;
                $i++;
            endforeach;
        else: ?>

<div class="color-aaa">
    There is nothing in ye archives
</div>

<?php   endif; ?>