<?php   if ( count( $events ) ):
            foreach ( $events as $event ):
                $event_date = strtotime( $event->event_date ); ?>

<div class="full-event padding-bottom-20 margin-bottom-20 position-relative">
<?php           if ( ! isset( $suppressSideDate ) ): ?>
    <div class="position-absolute side-date">
        <div class="day-name color-999 uppercase font-mono">
            <?php echo date( "l", $event_date ); ?>
        </div>
        <div class="day-month">
            <?php echo date( "n/j", $event_date ); ?>
        </div>
<?php               if ( valid( $event->event_time, STRING ) ): ?>
        <div class="time color-999 fontsize-13">
            <?php echo $event->getShortTime(); ?>
        </div>
<?php               endif; ?>
    </div>
<?php           endif; ?>
    <a class="blocked banner-wrap margin-bottom-15" href="<?php echo $event->getPath(); ?>"
        style="background-image: url( '<?php echo $event->getImage()->getPath( 960 ); ?>' );"></a>
    <h2 class="font-mono uppercase margin-bottom-10">
        <a href="<?php echo $event->getPath(); ?>" class="color-333 hover-underline"><?php echo $event->title; ?></a>
    </h2>
    <div class="date fontsize-15 color-999">
        <?php echo date( DATE_DAY_NAME_YEAR, $event_date ); ?>
<?php           if ( valid( $event->event_date_end, DATE ) ): ?>
        &mdash;
        <?php echo date( DATE_DAY_NAME_YEAR, strtotime( $event->event_date_end ) ); ?>
<?php           endif; ?>
    </div>
<?php           if ( valid( $event->event_time, STRING ) ): ?>
    <div class="date fontsize-15 color-999 margin-top-5">
        <span class="margin-left-1"><?php echo $event->getShortTime(); ?></span>
    </div>
<?php           endif; ?>
    <div class="body margin-top-10 lineheight-20">
        <?php echo ( strlen( $event->excerpt ) ) ? $event->excerpt : substr( $event->body, 0, 120 ); ?>
    </div>
</div>

<?php       endforeach;
        else: ?>
<div class="color-aaa">
    There are no upcoming <?php echo ( isset( $noneKeyword ) ) ? $noneKeyword : 'events'; ?>
</div>
<?php   endif; ?>