
<div id="admin" class="page">
    <!-- Edit form -->
    <form id="edit-form" class="clearfix" action="<?php echo $this->url->get( 'admin/articles/save' ); ?>"
        method="post" enctype="multipart/form-data">
        <div style="display:none;">
            <input type="hidden" name="id" value="<?php echo $post->id; ?>" />
        </div>

        <!-- Left col -->
        <div class="left-col float-left">
            <!-- General -->
            <fieldset class="margin-bottom-40">
                <legend>
                    <h2>General</h2>
                </legend>
                <div class="margin-bottom-20">
                    <label>Title</label>
                    <input class="w95p" type="text" name="title" value="<?php echo $post->title; ?>" />
                </div>
                <div class="margin-bottom-20">
                    <label>Excerpt/Subtitle</label>
                    <textarea class="w95p h50px" name="excerpt"><?php echo $post->excerpt; ?></textarea>
                </div>
                <div class="margin-bottom-20">
                    <label>Body/Content</label>
                    <textarea class="w95p h150px" name="body"><?php echo $post->body; ?></textarea>
                </div>
                <div>
                    <label>Status</label>
                    <div class="margin-bottom-5">
                        <input type="radio" name="status" value="draft"
                            <?php echo ( $post->status == 'draft' ) ? ' checked="checked"' : ''; ?> />
                        <span>Draft</span>
                    </div>
                    <div>
                        <input type="radio" name="status" value="published"
                            <?php echo ( $post->status == 'published' ) ? ' checked="checked"' : ''; ?> />
                        <span>Published</span>
                    </div>
                </div>
            </fieldset>

            <!-- Dates and Meta -->
            <fieldset class="margin-bottom-40">
                <legend>
                    <h2>Dates &amp; Meta</h2>
                </legend>
                <div class="clearfix margin-bottom-20">
                    <div class="float-left w33p">
                        <div class="margin-bottom-20">
                            <label>Post Date (displays on site)</label>
                            <input class="w150px datepicker" type="text" name="post_date"
                                value="<?php echo date_str( $post->post_date, DATE_PICKER, TRUE ); ?>" />
                        </div>
                    </div>
                    <div class="float-right w67p">
                        <div class="clearfix margin-bottom-20">
                            <label>Event Date (for searching events)</label>
                            <div class="float-left">
                                <input class="w150px datepicker" type="text" name="event_date"
                                    value="<?php echo date_str( $post->event_date, DATE_PICKER, TRUE ); ?>"
                                    placeholder="Event date..." />
                                <br />
<?php   if ( valid( $post->event_time, STRING ) ): ?>
                                <input class="w150px timepicker" type="text" name="event_time"
                                    value="<?php echo date_str( $post->event_time, DATE_TIME_PICKER, TRUE ); ?>"
                                    placeholder="Start time..." />
<?php   else: ?>
                                <a href="javascript:;" class="fontsize-13 set-time">Set time</a>
                                <input class="w150px timepicker" type="text" name="event_time" value=""
                                    style="display:none;" placeholder="Start time..." />
<?php   endif; ?>
                            </div>
<?php   if ( valid( $post->event_date_end, DATE )
            || valid( $post->event_time_end, STRING ) ): ?>
                            <div class="float-left margin-left-10 margin-right-10 padding-top-10">to</div>
                            <div class="float-left">
                                <input class="w150px datepicker" type="text" name="event_date_end"
                                    value="<?php echo date_str( $post->event_date_end, DATE_PICKER, TRUE ); ?>" />
                                <br />
<?php       if ( valid( $post->event_time_end, STRING ) ): ?>
                                <input class="w150px timepicker" type="text" name="event_time_end"
                                    value="<?php echo date_str( $post->event_time_end, DATE_TIME_PICKER, TRUE ); ?>"
                                    placeholder="End time..." />
<?php       else: ?>
                                <a href="javascript:;" class="fontsize-13 set-time">Set time</a>
                                <input class="w150px timepicker" type="text" name="event_time_end" value=""
                                    style="display:none;" placeholder="End time..." />
<?php       endif; ?>
                            </div>
<?php   else: ?>
                            <div class="float-left">
                                <a href="javascript:;" id="set-event-end-date"
                                    class="float-left blocked margin-left-10 margin-top-10">Set an ending date or time</a>
                                <div style="display:none;" class="clearfix">
                                    <div class="float-left margin-left-10 margin-right-10 padding-top-10">to</div>
                                    <div class="float-left">
                                        <input class="w150px datepicker" type="text" name="event_date_end" value=""
                                            placeholder="Ending date..." />
                                        <br />
<?php       if ( valid( $post->event_time_end, STRING ) ): ?>
                                        <input class="w150px timepicker" type="text" name="event_time_end"
                                            value="<?php echo date_str( $post->event_time_end, DATE_TIME_PICKER, TRUE ); ?>"
                                            placeholder="End time..." />
<?php       else: ?>
                                        <a href="javascript:;" class="fontsize-13 set-time">Set time</a>
                                        <input class="w150px timepicker" type="text" name="event_time_end" value=""
                                            style="display:none;" placeholder="End time..." />
<?php       endif; ?>
                                    </div>
                                </div>
                            </div>
<?php   endif; ?>
                        </div>
                    </div>
                </div>
                <div class="clearfix">
                    <div class="float-left w33p">
                        <label>Display on Homepage?</label>
                        <div class="margin-bottom-5">
                            <input type="radio" name="homepage_location" value="hero"
                                <?php echo ( $post->homepage_location == 'hero' ) ? ' checked="checked"' : ''; ?>/>
                            <span>Hero Filmstrip</span>
                        </div>
                        <div class="margin-bottom-5">
                            <input type="radio" name="homepage_location" value="boxes"
                                <?php echo ( $post->homepage_location == 'boxes' ) ? ' checked="checked"' : ''; ?> />
                            <span>Feature Boxes</span>
                        </div>
                        <div>
                            <input type="radio" name="homepage_location" value=""
                                <?php echo ( ! $post->homepage_location ) ? ' checked="checked"' : ''; ?> />
                            <em>None</em>
                        </div>
                    </div>
                    <div class="float-right w67p">
                        <div class="margin-bottom-20">
                            <label>Facebook/External URL</label>
                            <input class="w95p" type="text" name="external_url" value="<?php echo $post->external_url; ?>"
                                placeholder="http://..." />
                        </div>
                        <div>
<?php   if ( ! valid( $post->location, STRING ) ): ?>
                            <a href="javascript:;" id="set-location"
                                class="float-left blocked fontsize-13">Set specific event location (i.e. Pleasure Jail)</a>
                            <div style="display:none;">
<?php   else: ?>
                            <div>
<?php   endif; ?>
                                <label>Event Location</label>
                                <input class="w50p" type="text" name="location" value="<?php echo $post->location; ?>" />
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>

            <!-- Images -->
            <fieldset>
                <legend>
                    <h2>Photos</h2>
                </legend>
                <div class="clearfix">
                    <div class="float-left">
<?php   $image = $post->getImage();
        if ( valid( $image->id ) ): ?>
                        <div class="margin-bottom-5"><?php echo substr( $image->filename_orig, 0, 32 ); ?></div>
                        <div class="margin-bottom-5"><?php echo human_bytes( $image->size ); ?></div>
                        <div class="margin-bottom-5"><?php echo $image->mime_type; ?></div>
                        <div class="margin-bottom-25">Uploaded on <?php echo date_str( $image->created_at, DATE_DAY_NAME_YEAR ); ?></div>
<?php   endif; ?>
                        <input name="image" type="file" id="image-input" />

                        <div class="margin-top-20">
                            <label>Or enter an image URL:</label>
                            <input class="w90p" type="text" name="image_url" value="">
                        </div>

<?php   if ( valid( $image->id ) ): ?>
                        <div class="margin-top-30">
                            <a class="button gray" href="javascript:;" id="open-cropper">Crop Image</a>
                        </div>
<?php   endif; ?>
                    </div>
                    <div class="float-right clearfix" id="image-preview"
                        style="background-image:url('<?php echo $image->getPath(); ?>');">
                    </div>
                </div>
            </fieldset>
        </div><!-- /left-col -->

        <!-- Right col -->
        <div class="right-col float-right">
            <!-- Categories -->
            <fieldset class="margin-bottom-20">
                <legend>
                    <h2>Categories</h2>
                </legend>
<?php   $selected = FALSE;
        $catPicked = FALSE;
        foreach ( $categories as $category ):
            $selected = in_array( $category->slug, $postCategories );
            $catPicked = $catPicked || $selected;
            if ( $this->auth->getUserObj()->canAccessCategory( $category->id ) ): ?>
                <div class="margin-bottom-5">
                    <label>
                        <input type="radio" name="categories" value="<?php echo $category->slug; ?>"
                            <?php echo ( $selected ) ? ' checked="checked"' : ''; ?>/>
                        <span class="fontsize-16"><?php echo $category->name; ?></span>
                    </label>
                </div>
<?php       endif;
        endforeach; ?>
                <div class="margin-bottom-5">
                    <label>
                        <input type="radio" name="categories" value=""
                            <?php echo ( $catPicked ) ? '' : ' checked="checked"'; ?>/>
                        <em class="fontsize-16">None</em>
                    </label>
                </div>
            </fieldset>

            <!-- Tags -->
            <fieldset class="margin-bottom-20">
                <legend>
                    <h2>Tags</h2>
                </legend>
                <div class="margin-bottom-10">
                    <input id="tag-ac" data-field="tags" type="text" value="" class="w90p" placeholder="Type, then hit <enter>..." />
                </div>
                <div class="slug-wrapper">
<?php   foreach ( $post->getTags() as $tag ): ?>
                    <span class="tag">
                        <input type="hidden" name="tags[]" value="<?php echo $tag->name; ?>" />
                        <?php echo $tag->name; ?><i class="fa fa-times remove-slug"></i>
                    </span>
<?php   endforeach; ?>
                </div>
            </fieldset>

            <!-- Artists -->
            <fieldset class="margin-bottom-40">
                <legend>
                    <h2>Artists</h2>
                </legend>
                <div class="margin-bottom-10">
                    <input id="artist-ac" data-field="artists" type="text" value="" class="w90p" placeholder="Type, then hit <enter>..." />
                </div>
                <div class="slug-wrapper">
<?php   foreach ( $post->getArtists() as $artist ): ?>
                    <span class="tag">
                        <input type="hidden" name="artists[]" value="<?php echo $artist->name; ?>" />
                        <?php echo $artist->name; ?><i class="fa fa-times remove-slug"></i>
                    </span>
<?php   endforeach; ?>
                </div>
            </fieldset>
        </div><!-- /right-col -->

        <!-- Clearing div -->
        <div class="clearboth"></div>

        <!-- Image cropper -->
        <div id="cropper" class="margin-top-40" style="display:none;">
            <fieldset>
                <legend>
                    <h2>Crop Image</h2>
                </legend>
                <div class="clearfix position-relative">
                    <!-- Floated left -->
                    <div id="image-crop-wrap">
                        <img id="image-crop" src="<?php echo $image->getPath(); ?>" />
                    </div>
                    <!-- Floated right -->
                    <div id="image-crop-tools">
                        <!-- Cancel the cropper -->
                        <div class="margin-bottom-40">
                            <a class="red button" href="javascript:;" id="cancel-cropper">Cancel Cropping</a>
                        </div>
                        <div class="margin-bottom-20">
                            <em>Recommended minimum is <strong>960px</strong> wide by <strong>310px</strong> high!!!</em>
                        </div>
                        <div class="margin-bottom-10">
                            <span>Width:</span>
                            <strong id="ic_w"></strong>
                        </div>
                        <div>
                            <span>Height:</span>
                            <strong id="ic_h"></strong>
                        </div>
                        <!-- Hidden crop coordinates -->
                        <div style="display:none;">
                            <input id="ic_x1" type="hidden" name="crop_x1" value="" />
                            <input id="ic_x2" type="hidden" name="crop_x2" value="" />
                            <input id="ic_y1" type="hidden" name="crop_y1" value="" />
                            <input id="ic_y2" type="hidden" name="crop_y2" value="" />
                        </div>
                    </div>
                </div>
            </fieldset>
        </div>
    </form>

    <!-- Delete -->
    <div class="righted-text padding-top-30 margin-top-30" id="delete-wrapper">
        <a class="fontsize-18 red button" href="javascript:;" id="delete-object">
            Delete Article
        </a>
        <a class="fontsize-18 black button" href="<?php echo $this->url->get( "admin/articles/delete/{$post->id}" ); ?>"
            id="really-delete-object" style="display:none;">
            Click again to confirm
        </a>
    </div>
</div>

<script>
<?php   $tagObjects = [];
        foreach ( $tags as $tag ):
            $tagObjects[] = [ 'name' => $tag->name ];
        endforeach; ?>
    var tags = <?php echo json_encode( $tagObjects ); ?>;

<?php   $artistObjects = [];
        foreach ( $artists as $artist ):
            $artistObjects[] = [ 'name' => $artist->name ];
        endforeach; ?>
    var artists = <?php echo json_encode( $artistObjects ); ?>;
</script>