
<div id="admin" class="page">
    <!-- Edit form -->
    <form id="edit-form" class="clearfix" action="<?php echo $this->url->get( 'admin/save' ); ?>"
        method="post" enctype="multipart/form-data">
        <div style="display:none;">
            <input type="hidden" name="id" value="<?php echo $post->id; ?>" />
        </div>

        <!-- Left col -->
        <div class="left-col float-left">
            <!-- General -->
            <fieldset class="margin-bottom-40">
                <legend>
                    <h2>General</h2>
                </legend>
                <div class="margin-bottom-20">
                    <label>Title</label>
                    <input class="w95p" type="text" name="title" value="<?php echo $post->title; ?>" />
                </div>
                <div class="margin-bottom-20">
                    <label>Excerpt/Subtitle</label>
                    <textarea class="w95p h50px" name="excerpt"><?php echo $post->excerpt; ?></textarea>
                </div>
                <div class="margin-bottom-20">
                    <label>Body/Content</label>
                    <textarea class="w95p h150px" name="body"><?php echo $post->body; ?></textarea>
                </div>
                <div>
                    <label>Status</label>
                    <div class="margin-bottom-5">
                        <input type="radio" name="status" value="draft"
                            <?php echo ( $post->status == 'draft' ) ? ' checked="checked"' : ''; ?> />
                        <span>Draft</span>
                    </div>
                    <div>
                        <input type="radio" name="status" value="published"
                            <?php echo ( $post->status == 'published' ) ? ' checked="checked"' : ''; ?> />
                        <span>Published</span>
                    </div>
                </div>
            </fieldset>

            <!-- Dates and Meta -->
            <fieldset class="margin-bottom-40">
                <legend>
                    <h2>Dates &amp; Meta</h2>
                </legend>
                <div class="clearfix margin-bottom-20">
                    <div class="float-left w50p">
                        <div class="margin-bottom-20">
                            <label>Post Date (displays on site)</label>
                            <input class="w150px datepicker" type="text" name="post_date"
                                value="<?php echo date_str( $post->post_date, DATE_PICKER, TRUE ); ?>" />
                        </div>
                    </div>
                    <div class="float-right w50p">
                        <div>
                            <label>Event Date (for searching events)</label>
                            <input class="w150px datepicker" type="text" name="event_date"
                                value="<?php echo date_str( $post->event_date, DATE_PICKER, TRUE ); ?>" />
                        </div>
                    </div>
                </div>
                <div>
                    <label>Display on Homepage?</label>
                    <div class="margin-bottom-5">
                        <input type="radio" name="homepage_location" value="hero"
                            <?php echo ( $post->homepage_location == 'hero' ) ? ' checked="checked"' : ''; ?>/>
                        <span>Hero Filmstrip</span>
                    </div>
                    <div class="margin-bottom-5">
                        <input type="radio" name="homepage_location" value="boxes"
                            <?php echo ( $post->homepage_location == 'boxes' ) ? ' checked="checked"' : ''; ?> />
                        <span>Feature Boxes</span>
                    </div>
                    <div>
                        <input type="radio" name="homepage_location" value=""
                            <?php echo ( ! $post->homepage_location ) ? ' checked="checked"' : ''; ?> />
                        <em>None</em>
                    </div>
                </div>
            </fieldset>

            <!-- Images -->
            <fieldset>
                <legend>
                    <h2>Photos</h2>
                </legend>
                <div class="clearfix">
                    <div class="float-left">
<?php   $image = $post->getImage();
        if ( valid( $image->id ) ): ?>
                        <div class="margin-bottom-5"><?php echo $image->filename_orig; ?></div>
                        <div class="margin-bottom-5"><?php echo human_bytes( $image->size ); ?></div>
                        <div class="margin-bottom-5"><?php echo $image->mime_type; ?></div>
                        <div class="margin-bottom-25">Uploaded on <?php echo date_str( $image->created_at, DATE_DAY_NAME_YEAR ); ?></div>
<?php   endif; ?>
                        <input name="image" type="file" id="image-input" />
                    </div>
                    <div class="float-right clearfix" id="image-preview">
                        <img src="<?php echo $image->getPath(); ?>" />
                        <span>No picture selected</span>
                    </div>
                </div>
            </fieldset>
        </div><!-- /left-col -->

        <!-- Right col -->
        <div class="right-col float-right">
            <!-- Categories -->
            <fieldset class="margin-bottom-20">
                <legend>
                    <h2>Categories</h2>
                </legend>
<?php   $selected = FALSE;
        $catPicked = FALSE;
        foreach ( $categories as $category ):
            $selected = in_array( $category->slug, $postCategories );
            $catPicked = $catPicked || $selected; ?>
                <div class="margin-bottom-5">
                    <label>
                        <input type="radio" name="categories" value="<?php echo $category->slug; ?>"
                            <?php echo ( $selected ) ? ' checked="checked"' : ''; ?>/>
                        <span class="fontsize-16"><?php echo $category->name; ?></span>
                    </label>
                </div>
<?php   endforeach; ?>
                <div class="margin-bottom-5">
                    <label>
                        <input type="radio" name="categories" value=""
                            <?php echo ( $catPicked ) ? '' : ' checked="checked"'; ?>/>
                        <em class="fontsize-16">None</em>
                    </label>
                </div>
            </fieldset>

            <!-- Tags -->
            <fieldset class="margin-bottom-20">
                <legend>
                    <h2>Tags</h2>
                </legend>
            </fieldset>

            <!-- Artists -->
            <fieldset class="margin-bottom-40">
                <legend>
                    <h2>Artists</h2>
                </legend>
            </fieldset>

            <!-- Delete -->
            <div class="righted-text">
                <a class="fontsize-18 red button" href="javascript:;" id="delete-post">
                    Delete Article
                </a>
                <a class="fontsize-18 black button" href="<?php echo $this->url->get( "admin/delete/{$post->id}" ); ?>"
                    id="really-delete-post" style="display:none;">
                    Click again to confirm
                </a>
            </div>
        </div><!-- /right-col -->
    </form>
</div>