<!-- AIR Swap Partnershi[] Page -->
<div class="page clearfix">
    <h1 class="margin-bottom-25 font-mono uppercase">AIR Swap Partnership</h1>
    <!-- w47p float-left lineheight-24 -->
    <!-- Images -->
    <div class="float-right margin-left-15 padding-left-20 margin-bottom-10 clearfix">
        <div class="float-left">
            <a href="<?php echo $this->url->getStatic( 'img/airswap/airswap_1.jpg' ); ?>">
                <img src="<?php echo $this->url->getStatic( 'img/airswap/airswap_1_240x160.jpg' ); ?>"
                    width="240" height="160" />
            </a>
        </div>
        <div class="margin-left-15 lineheight-24 float-left">
            <a href="<?php echo $this->url->getStatic( 'img/airswap/airswap_2.jpg' ); ?>">
                <img src="<?php echo $this->url->getStatic( 'img/airswap/airswap_2_240x160.jpg' ); ?>"
                    width="240" height="160" />
            </a>
        </div>
    </div>
    <div class="float-right margin-left-15 padding-left-20 margin-bottom-10 clearfix">
        <div class="lineheight-24 float-left">
            <a href="<?php echo $this->url->getStatic( 'img/airswap/airswap_3.jpg' ); ?>">
                <img src="<?php echo $this->url->getStatic( 'img/airswap/airswap_3_240x160.jpg' ); ?>"
                    width="240" height="160" />
            </a>
        </div>
        <div class="margin-left-15 lineheight-24 float-left">
            <a href="<?php echo $this->url->getStatic( 'img/airswap/airswap_4.jpg' ); ?>">
                <img src="<?php echo $this->url->getStatic( 'img/airswap/airswap_4_240x160.jpg' ); ?>"
                    width="240" height="160" />
            </a>
        </div>
    </div>
    <!-- Content -->
    <div class="margin-bottom-15 lineheight-24">
        The Silent Barn is excited to announce our new exchange program with
        The Museum of Human Achievement, in Austin TX.
    </div>
    <div class="margin-bottom-15 lineheight-24">
        AIR Swap is now accepting applications in all mediums for a rotating
        monthly residency program for a one month residency in Austin TX.
    </div>
    <div class="margin-bottom-15 lineheight-24 centered-text">
       <a href="http://www.tfaforms.com/340274">Find the Application here</a>
    </div>
    <div class="margin-bottom-15 lineheight-24">
        The Museum of Human Achievement is a multi-disciplinary arts space.
        That offers a beautifully refined 7500 sq ft. pier and beam warehouse
        (previously a sex toy factory) with tough as nails hardwood floors.
    </div>
    <div class="margin-bottom-15 lineheight-24">
        Think less nightclub, more cult.<br>
        What can you do with all this creative space?
    </div>
    <div class="lineheight-24">
        <a href="http://themuseumofhumanachievement.com/">More Info @ themuseumofhumanachievement.com</a>
    </div>
</div>