<!-- Stewdios Applications Page -->
<div class="page clearfix">
    <h1 class="margin-bottom-25 font-mono uppercase">Stewdios Applications</h1>

    <div class="margin-bottom-15 lineheight-24">
        Silent Barn Stewdios are not typical artist studios. Silent Barn is a
        collective, best for people who thrive on a constant buzz of activity.
        We attempt to provide secure spaces for focused creativity, while
        simultaneously engaging our Stewdios as part of the Silent Barn family.
        We are collaborators and co-conspirators, helping to engage the public
        visiting our space every night. We're not just here to work &mdash;
        we're here to exhibit a vision of life and creation very different than
        how the world tells us things should work.
    </div>

    <div class="margin-bottom-15 lineheight-24">
        On the ground floor space of our three floor compound, over twenty
        individual Stewdios share spaces for co-working. Our yard and
        performance space, active daily, make for high visibility workspaces
        &mdash; aside from working artists, we're able to sustain galleries,
        stores and production companies. Everything from a synthesizer factory,
        painters, recording studio and barbershop share our ground floor
        Stewdios.
    </div>

    <div class="margin-bottom-15 lineheight-24">
        Upstairs, we have four 2-bedroom apartments filled with artists who
        create their own work, host creative projects in their living rooms,
        and are core participants in the Silent Barn collective.
    </div>

    <div class="clearfix">
        <div class="w47p float-left bg-eee padding-all-1p">
            <h3>To live at Silent Barn</h3>
            <div class="lineheight-24">
                We do not currently have any openings for new residents at
                Silent Barn. Stay tuned! We will have openings in the Summer
                and Fall.
                We're currently accepting applications on a rolling basis,
                although availability is tight. To apply,
                <a href="http://www.tfaforms.com/349412">please fill out this form</a>.
                If you've got any questions, email the Residents at
                <a href="mailto:silentbarnresidents@googlegroups.com">silentbarnresidents@googlegroups.com</a>.
            </div>
        </div>

        <div class="w47p float-right bg-eee padding-all-1p">
            <h3>To work at Silent Barn</h3>
            <div class="lineheight-24 margin-bottom-15">
                We currently have one stewdio available for rent in the "North
                Garage", sharing a space with Deep Cuts (Barbershop and Record
                Store) and The Center For Strategic Art and Architecture (art
                gallery and community garden).
            </div>
            <div class="lineheight-24">
                <a href="https://docs.google.com/spreadsheet/viewform?formkey=dHRiZXJvZjBpSXVqVjk0b29ya0VwWFE6MQ#gid=0">Apply for that stewdio here</a>.
                We will also have an opening the summer for a space in our
                "South Garage".
            </div>
        </div>
    </div>
</div>
