<!-- Living Stewdios Page -->
<div class="page clearfix">
    <h1 class="margin-bottom-25 font-mono uppercase">Living Stewdios</h1>

    <div class="margin-bottom-15 lineheight-24">
        Upstairs we have a thriving artist in residency program. Four 2-bedroom apartments
        filled with artists who create their own work, including interactive art, music,
        zine production, sound art, neuroscience art, video art, circuit building and more.
    </div>
    <div class="margin-bottom-30 lineheight-24">
        Silent Bar AIRS host creative projects in their living rooms, and are core participants
        in the Silent Barn collective. Here are some of the past and present artists in residence.
    </div>

<?php   $this->partial(
            'partials/spaces/blocks', [
                'spaces' => $spaces,
                'noneNoun' => 'living studios'
            ]); ?>
</div>
