<!-- Working Stewdios Page -->
<div class="page clearfix">
    <h1 class="margin-bottom-25 font-mono uppercase">Working Stewdios</h1>

    <div class="margin-bottom-30 lineheight-24">
        On the ground floor space of our three floor building, over twenty individual
        Stewdios share spaces for co-working. Our yard and performance space, active daily,
        make for high visibility workspaces &mdash; aside from working artists, we're able to
        sustain galleries, stores and production companies. Everything from a synthesizer factory,
        painters, recording studio and barbershop share our ground floor Stewdios.
    </div>

    <?php   $this->partial(
            'partials/spaces/blocks', [
                'spaces' => $spaces,
                'noneNoun' => 'working stewdios'
            ]); ?>
</div>
