<!-- Spaces list -->
<div id="spaces" class="spaces clearfix">
<?php   $archived_count = 0;
        if ( ! count( $spaces ) ): ?>

    <div class="color-aaa">
        There are no <?php echo $noneNoun; ?>
    </div>

<?php   else:
            $i = 1;
            foreach ( $spaces as $space ):
                if ( $space->is_archived ):
                    $archived_count++;
                    continue;
                endif;
                $image = ( $space->hasImage() )
                    ? $space->getImagePath( 310 )
                    : $this->url->getStatic( 'img/heptagon_placeholder_231.png' ); ?>

    <div class="space float-left" rel="leanModal" data-target="#space-<?php echo $space->id; ?>">
        <div class="img-wrap">
            <img src="<?php echo $image; ?>" />
            <h3 class="name"><?php echo $space->name; ?></h3>
        </div>
        <div class="more-info" style="display:none;" id="space-<?php echo $space->id; ?>">
            <div class="space-callout clearfix">
                <!-- Image, email, and website -->
                <div class="meta-wrap">
                    <!-- Image -->
                    <div class="margin-bottom-20">
                        <img src="<?php echo $image; ?>" />
                    </div>
<?php   if ( valid( $space->email, STRING ) ): ?>
                    <!-- Email -->
                    <div class="row padding-left-20 position-relative margin-bottom-10 fontsize-14">
                        <i class="fa fa-envelope margin-right-5 color-aaa"></i>
                        <a class="break-word" href="mailto:<?php echo $space->email; ?>"><?php echo $space->email; ?></a>
                    </div>
<?php   endif;
        if ( valid( $space->website, STRING ) ): ?>
                    <!-- Website -->
                    <div class="row padding-left-20 position-relative margin-bottom-10 fontsize-14">
                        <i class="fa fa-external-link margin-right-5 color-aaa"></i>
                        <a class="break-word" href="<?php echo $space->website; ?>" target="_blank"><?php echo $space->website; ?></a>
                    </div>
<?php   endif; ?>
                </div><!-- /meta wrapper -->

                <!-- Long form content -->
                <div class="content-wrap">
                    <!-- Name -->
                    <h1><?php echo $space->name; ?></h1>

                    <!-- Subtitle -->
<?php   if ( valid( $space->subtitle, STRING ) ): ?>
                    <h4><?php echo $space->subtitle; ?></h4>
<?php   endif; ?>

                    <!-- Bio -->
                    <div class="padding-top-10 lineheight-24 margin-bottom-20">
                        <?php echo ( valid( $space->bio, STRING ) ) ? $space->getHtmlBio() : 'Nothing to see here&hellip;'; ?>
                    </div>
                </div><!-- space callout -->
            </div><!-- content wrapper -->
        </div><!-- /more info -->
    </div><!-- /space -->

<?php           $i++;
                if ( $i > 4 ):
                    $i = 1;
                endif;
            endforeach;
        endif; ?>
</div><!-- Spaces -->

<?php   if ( $archived_count ): ?>
<!-- Archived Spaces -->
<h1 class="margin-bottom-25 margin-top-40 font-mono uppercase">Past <?php echo $noneNoun; ?></h1>
<div id="archived-paces" class="spaces clearfix">
<?php       $i = 1;
            foreach ( $spaces as $space ):
                if ( ! $space->is_archived ):
                    continue;
                endif;
                $image = ( $space->hasImage() )
                    ? $space->getImagePath( 310 )
                    : $this->url->getStatic( 'img/heptagon_placeholder_231.png' ); ?>

    <div class="space float-left" rel="leanModal" data-target="#space-<?php echo $space->id; ?>">
        <div class="img-wrap">
            <img src="<?php echo $image; ?>" />
            <h3 class="name"><?php echo $space->name; ?></h3>
        </div>
        <div class="more-info" style="display:none;" id="space-<?php echo $space->id; ?>">
            <div class="space-callout clearfix">
                <!-- Image, email, and website -->
                <div class="meta-wrap">
                    <!-- Image -->
                    <div class="margin-bottom-20">
                        <img src="<?php echo $image; ?>" />
                    </div>
<?php   if ( valid( $space->email, STRING ) ): ?>
                    <!-- Email -->
                    <div class="row padding-left-20 position-relative margin-bottom-10 fontsize-14">
                        <i class="fa fa-envelope margin-right-5 color-aaa"></i>
                        <a class="break-word" href="mailto:<?php echo $space->email; ?>"><?php echo $space->email; ?></a>
                    </div>
<?php   endif;
        if ( valid( $space->website, STRING ) ): ?>
                    <!-- Website -->
                    <div class="row padding-left-20 position-relative margin-bottom-10 fontsize-14">
                        <i class="fa fa-external-link margin-right-5 color-aaa"></i>
                        <a class="break-word" href="<?php echo $space->website; ?>" target="_blank"><?php echo $space->website; ?></a>
                    </div>
<?php   endif; ?>
                </div><!-- /meta wrapper -->

                <!-- Long form content -->
                <div class="content-wrap">
                    <!-- Name -->
                    <h1><?php echo $space->name; ?></h1>

                    <!-- Subtitle -->
<?php   if ( valid( $space->subtitle, STRING ) ): ?>
                    <h4><?php echo $space->subtitle; ?></h4>
<?php   endif; ?>

                    <!-- Bio -->
                    <div class="padding-top-10 lineheight-24 margin-bottom-20">
                        <?php echo ( valid( $space->bio, STRING ) ) ? $space->getHtmlBio() : 'Nothing to see here&hellip;'; ?>
                    </div>
                </div><!-- space callout -->
            </div><!-- content wrapper -->
        </div><!-- /more info -->
    </div><!-- /space -->

<?php           $i++;
                if ( $i > 4 ):
                    $i = 1;
                endif;
            endforeach;
        endif; ?>
</div><!-- Archived Spaces -->