<!-- #footer -->
<div id="footer-wrap">
    <footer class="clearfix">
        <div class="left">
            <div class="font-mono name">Silent Barn</div>
            <div class="font-monp address">603 Bushwick Ave, New York, NY 11206</div>
            <div class="font-mono legal">&copy; 2013 Silent Barn, LLC. All Rights Reserved</div>
        </div>
        <div class="right">
            <img src="<?php echo $this->url->get( 'img/map.png' ); ?>" width="160" />
        </div>
    </footer>
</div>
