<!-- Mobile navigation -->
<div id="mobile-nav" style="display:none;">
    <ul>
        <?php
        $this->partial( 'partials/nav' ); ?>
    </ul>
</div>

<!-- Header -->
<div id="header-wrap">
    <header>
        <!-- Logo -->
        <div id="logo">
            <a href="<?php echo $this->url->get( '' ); ?>">
                <img class="large transition-bottom" src="<?php echo $this->url->getStatic( 'img/logo_160w.png' ); ?>"
                    width="160" alt="Silent Barn Logo" />
                <img class="small transition-top" src="<?php echo $this->url->getStatic( 'img/logo_40w.png' ); ?>"
                    width="40" alt="Silent Barn Logo" />
            </a>
        </div>
        <!--
        <div id="announcement">
            <h3 class="font-mono uppercase">
                <a class="color-333" href="<?php echo $this->url->get( '2015/09/fire-aftermath' ); ?>">Fire Aftermath &amp; Updates</a>
            </h3>
            <a class="fontsize-16 green button submit-paypal" href="javascript:;">
                Donate
            </a>
        </div>
        -->

        <div id="support-barn">
            <div class="message">
                <span class="font-mono fontsize-16 uppercase color-999">Support the Barn</span>
            </div>
            <a class="green button fontsize-14" href="https://withfriends.co/silent_barn/join">Donate!</a>
            <!--
            <a class="green button fontsize-12 submit-paypal" href="javascript:;">Donate!</a>
            <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top" style="display:none;">
                <input type="hidden" name="cmd" value="_s-xclick">
                <input type="hidden" name="hosted_button_id" value="V3TCPFJM6MZSS">
            </form>
            -->
        </div>

        <!-- For small screens -->
        <a id="mobile-burger" href="javascript:;" class="mobile-menu-button hide">
            <i class="fa fa-bars"></i>
        </a>

        <!-- Social icons -->
        <div id="social-icons" class="social-icons">
            <a href="http://silentbarn.us6.list-manage.com/subscribe?u=63105f245b09f724f3b2b57bd&id=8af55871bb"
                class="font-mono fontsize-12 uppercase color-999">
                Mailing List!
            </a>
            <a class="facebook" href="https://www.facebook.com/silentbarn">
                <i class="fa fa-facebook-square"></i>
            </a>
            <a class="twitter" href="https://twitter.com/theSilentBarn">
                <i class="fa fa-twitter-square"></i>
            </a>
            <a class="tumblr" href="http://thesilentbarn.tumblr.com/">
                <i class="fa fa-tumblr-square"></i>
            </a>
            <a class="instagram" href="http://instagram.com/silentbarn">
                <i class="fa fa-instagram"></i>
            </a>
            <a class="youtube" href="https://www.youtube.com/user/SilentBarn">
                <i class="fa fa-youtube-square"></i>
            </a>
        </div>

        <!-- Navigation -->
        <nav>
            <ul id="menu">
                <?php
                $this->partial( 'partials/nav' ); ?>
            </ul>
            <form id="search" name="search" method="get" action="#" onsubmit="return false;">
                <input type="text" id="search-query" name="query" value=""
                    class="transition-width" placeholder="Search..."
                    data-siteurl="<?php echo $this->url->get( '' ); ?>" />
                <a href="javascript:;" id="search-submit">
                    <i class="fa fa-search"></i>
                </a>
            </form>
        </nav>
    </header>
</div>

<?php
if ( isset( $pageNav ) ):
    $this->partial(
        $pageNav[ 'partial' ],
        [
            'page' => $pageNav[ 'page' ]
        ]);
endif;

// Show any messages
$notifications = ( isset( $notifications ) && is_array( $notifications ) && count( $notifications ) )
    ? $notifications
    : [];
$notifications = array_merge( $notifications, $flashMessages );

if ( count( $notifications ) ): ?>

<div id="notif-messages">
    <?php
    foreach ( $notifications as $notification ): ?>
    <div class="message <?php echo key( $notification ); ?>"><?php echo current( $notification ); ?></div>
    <?php
    endforeach; ?>
</div>

<?php
endif; ?>