<!-- Header -->
<div id="header-wrap">
    <header>
        <!-- Logo -->
        <div id="logo">
            <img src="<?php echo $this->url->get( 'img/logo_160w.png' ); ?>" width="160" alt="Silent Barn Logo" />
        </div>
        <div id="photo-stream">
            <!--<iframe src="http://widget.stagram.com/in/silentbarn/?s=80&w=4&h=1&b=0&p=8"
                allowtransparency="true" frameborder="0" scrolling="no"
                style="border:none;overflow:hidden;width:360px; height: 90px" ></iframe>-->
        </div>
        <!-- Navigation -->
        <nav>
            <ul id="menu">
                <li>
                    <a href="#">Events</a>
                    <ul class="sub-menu">
                        <li><a href="#">Upcoming</a></li>
                        <li><a href="#">Archives</a></li>
                        <li><a href="#">Booking</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#">Stewdios</a>
                    <ul class="sub-menu">
                        <li><a href="#">Living Stewdios</a></li>
                        <li><a href="#">Working Stewdios</a></li>
                        <li><a href="#">About Stewdios</a></li>
                        <li><a href="#">Apply</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#">About</a>
                    <ul class="sub-menu">
                        <li><a href="#">About</a></li>
                        <li><a href="#">Mission</a></li>
                        <li><a href="#">Press</a></li>
                        <li><a href="#">Community</a></li>
                        <li><a href="#">Gallery</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#">Get Involved</a>
                    <ul class="sub-menu">
                        <li><a href="#">Donate</a></li>
                        <li><a href="#">Volunteer</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </li>
            </ul>
            <form id="search" method="post" action="">
                <input type="text" name="query" value="" placeholder="Search..." />
                <a href="#">
                    <i class="fa fa-search"></i>
                </a>
            </form>
        </nav>
    </header>
</div>
