<!-- Header -->
<div id="header-wrap">
    <header>
        <!-- Logo -->
        <div id="logo">
            <a href="<?php echo $this->url->get( '' ); ?>">
                <img class="large transition-bottom" src="<?php echo $this->url->getStatic( 'img/logo_160w.png' ); ?>"
                    width="160" alt="Silent Barn Logo" />
                <img class="small transition-top" src="<?php echo $this->url->getStatic( 'img/logo_40w.png' ); ?>"
                    width="40" alt="Silent Barn Logo" />
            </a>
        </div>

<?php   $this->partial( 'partials/photostream' ); ?>

        <div id="social-icons" class="social-icons">
            <a href="http://silentbarn.us6.list-manage.com/subscribe?u=63105f245b09f724f3b2b57bd&id=8af55871bb"
                class="font-mono fontsize-12 uppercase color-999">
                Mailing List!
            </a>
            <a class="facebook" href="https://www.facebook.com/silentbarn">
                <i class="fa fa-facebook-square"></i>
            </a>
            <a class="twitter" href="https://twitter.com/theSilentBarn">
                <i class="fa fa-twitter-square"></i>
            </a>
            <a class="tumblr" href="http://thesilentbarn.tumblr.com/">
                <i class="fa fa-tumblr-square"></i>
            </a>
            <a class="instagram" href="http://instagram.com/silentbarn">
                <i class="fa fa-instagram"></i>
            </a>
            <a class="youtube" href="http://thesilentbarn.tumblr.com/">
                <i class="fa fa-youtube-square"></i>
            </a>
            <?php /*
            <a class="calendar" href="#">
                <i class="fa fa-calendar"></i>
            </a> */ ?>
        </div>
        <!-- Navigation -->
        <nav>
            <ul id="menu">
                <li>
                    <a href="<?php echo $this->url->get( 'events' ); ?>">Events</a>
                    <ul class="sub-menu">
                        <li><a href="<?php echo $this->url->get( 'events/upcoming' ); ?>">Upcoming</a></li>
                        <li><a href="<?php echo $this->url->get( 'events/archives' ); ?>">Archives</a></li>
                        <li><a href="<?php echo $this->url->get( 'events/exhibitions' ); ?>">Exhibitions</a></li>
                        <li><a href="<?php echo $this->url->get( 'events/booking' ); ?>">Booking</a></li>
                    </ul>
                </li>
                <li>
                    <a href="<?php echo $this->url->get( 'stewdios/living' ); ?>">Stewdios</a>
                    <ul class="sub-menu">
                        <li><a href="<?php echo $this->url->get( 'stewdios/living' ); ?>">Living Stewdios</a></li>
                        <li><a href="<?php echo $this->url->get( 'stewdios/working' ); ?>">Working Stewdios</a></li>
                        <li><a href="<?php echo $this->url->get( 'stewdios/apply' ); ?>">Apply</a></li>
                    </ul>
                </li>
                <li>
                    <a href="<?php echo $this->url->get( 'about' ); ?>">Community</a>
                    <ul class="sub-menu">
                        <li><a href="<?php echo $this->url->get( 'about/chefs' ); ?>">Chefs</a></li>
                        <li><a href="<?php echo $this->url->get( 'about/mission' ); ?>">Mission</a></li>
                        <li><a href="<?php echo $this->url->get( 'about/press' ); ?>">Press</a></li>
                        <li><a href="<?php echo $this->url->get( 'about/gallery' ); ?>">Barn Art</a></li>
                    </ul>
                </li>
                <li>
                    <a href="javascript:;">Get Involved</a>
                    <ul class="sub-menu">
                        <li><a href="http://silentbarn.org/donate" target="_blank">Donate</a></li>
                        <li><a href="<?php echo $this->url->get( 'about/volunteer' ); ?>">Volunteer</a></li>
                        <li><a href="<?php echo $this->url->get( 'about/contact' ); ?>">Contact</a></li>
                    </ul>
                </li>
            </ul>
            <form id="search" name="search" method="get" action="#" onsubmit="return false;">
                <input type="text" id="search-query" name="query" value=""
                    class="transition-width" placeholder="Search..."
                    data-siteurl="<?php echo $this->url->get( '' ); ?>" />
                <a href="javascript:;" id="search-submit">
                    <i class="fa fa-search"></i>
                </a>
            </form>
        </nav>
    </header>
</div>
<?php   if ( isset( $pageNav ) ):
            $this->partial(
                $pageNav[ 'partial' ],
                [
                    'page' => $pageNav[ 'page' ]
                ]);
        endif; ?>
