<li>
    <a href="<?php echo $this->url->get( 'events' ); ?>">Events</a>
    <ul class="sub-menu">
        <li><a href="<?php echo $this->url->get( 'events/upcoming' ); ?>">Upcoming</a></li>
        <li><a href="<?php echo $this->url->get( 'events/archives' ); ?>">Archives</a></li>
        <li><a href="<?php echo $this->url->get( 'events/exhibitions' ); ?>">Exhibitions</a></li>
        <li><a href="<?php echo $this->url->get( 'events/booking' ); ?>">Booking</a></li>
    </ul>
</li>
<li>
    <a href="<?php echo $this->url->get( 'stewdios/living' ); ?>">Stewdios</a>
    <ul class="sub-menu">
        <li><a href="<?php echo $this->url->get( 'stewdios/living' ); ?>">Living Stewdios</a></li>
        <li><a href="<?php echo $this->url->get( 'stewdios/working' ); ?>">Working Stewdios</a></li>
        <li><a href="<?php echo $this->url->get( 'stewdios/apply' ); ?>">Apply</a></li>
        <li><a href="<?php echo $this->url->get( 'stewdios/airswap' ); ?>">AIR Swap Partnership</a></li>
    </ul>
</li>
<li>
    <a href="<?php echo $this->url->get( 'about' ); ?>">Community</a>
    <ul class="sub-menu">
        <li><a href="<?php echo $this->url->get( 'about/chefs' ); ?>">Chefs</a></li>
        <li><a href="<?php echo $this->url->get( 'about/mission' ); ?>">Mission</a></li>
        <li><a href="<?php echo $this->url->get( 'about/press' ); ?>">Press</a></li>
        <li><a href="<?php echo $this->url->get( 'about/gallery' ); ?>">Barn Art</a></li>
    </ul>
</li>
<li>
    <a href="javascript:;">Get Involved</a>
    <ul class="sub-menu">
        <li><a href="<?php echo $this->url->get( 'donate' ); ?>">Donate</a></li>
        <li><a href="<?php echo $this->url->get( 'about/volunteer' ); ?>">Volunteer</a></li>
        <li><a href="<?php echo $this->url->get( 'about/contact' ); ?>">Contact</a></li>
    </ul>
</li>