<!-- Hero/Carousel -->
<div id="hero" class="hero">
    <div id="hero-carousel" class="hero-carousel">
        <div class="slide">
            <img src="<?php echo $this->url->get( 'img/banner_sample_1.jpg' ); ?>" width="960" height="420" />
            <div class="blurb">
                <div class="clearfix">
                    <h1>
                        <span>Advaita Playing Like Every Week</span>
                    </h1>
                </div>
                <div class="clearfix">
                    <p>
                        This is a description. These are comletely optional but this is
                        what one would look like on the hero carousel.
                    </p>
                </div>
            </div>
        </div>
        <div class="slide">
            <img src="<?php echo $this->url->get( 'img/banner_sample_2.jpg' ); ?>" width="960" height="420" />
            <div class="blurb">
                <div class="clearfix">
                    <h1>
                        <span>Here is Another Header</span>
                    </h1>
                </div>
            </div>
        </div>
        <div class="slide">
            <img src="<?php echo $this->url->get( 'img/banner_sample_3.jpg' ); ?>" width="960" height="420" />
            <div class="blurb">
                <div class="clearfix">
                    <h1>
                        <span>A Third Header Goes Here -- Something Else!</span>
                    </h1>
                </div>
                <div class="clearfix">
                    <p>
                        Another description, this time shorter.
                    </p>
                </div>
            </div>
        </div>
        <div class="slide">
            <img src="<?php echo $this->url->get( 'img/banner_sample_3.jpg' ); ?>" width="960" height="420" />
            <div class="blurb">
                <div class="clearfix">
                    <h1>
                        <span>Same Image Again</span>
                    </h1>
                </div>
            </div>
        </div>
    </div>
    <div id="hero-nav" class="clearfix">
        <a href="javascript:;" id="carousel-next">&rarr;</a>
        <a href="javascript:;" id="carousel-prev">&larr;</a>
    </div>
</div>

<!-- Vignettes -->
<div id="vignettes">
    <div class="row clearfix">
        <div class="block">
            <img src="<?php echo $this->url->get( 'img/block_sample_1.jpg' ); ?>" width="310" height="240" />
            <div class="categories font-mono">
                <span>Events</span>
            </div>
            <h3 class="title font-mono">
                <a href="#">Welcome to the New Silent Barn!</a>
            </h3>
            <div class="date font-mono">
                Posted: February 10, 2014
            </div>
            <div class="description">
                Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium
                doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore
                veritatis et quasi architecto beatae vitae dicta sunt explicabo.
            </div>
        </div>
        <div class="block">
            <img src="<?php echo $this->url->get( 'img/block_sample_2.jpg' ); ?>" width="310" height="240" />
            <div class="categories font-mono">
                <span>Press</span>
            </div>
            <h3 class="title font-mono">
                <a href="#">Press and Event Meetings</a>
            </h3>
            <div class="date font-mono">
                Posted: February 3, 2014
            </div>
            <div class="description">
                We need to meet with the Press and Event teams to go over the new site and
                how to use the WordPress blog.
            </div>
        </div>
        <div class="block">
            <img src="<?php echo $this->url->get( 'img/block_sample_3.jpg' ); ?>" width="310" height="240" />
            <div class="categories font-mono">
                <span>Shows</span>
            </div>
            <h3 class="title font-mono">
                <a href="#">Advaita Playing This Weekend</a>
            </h3>
            <div class="date font-mono">
                Posted: February 14, 2014
            </div>
            <div class="description">
                Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium
                doloremque laudantium, totam rem aperiam, eaque ipsa quae.
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="block">
            <img src="<?php echo $this->url->get( 'img/block_sample_5.jpg' ); ?>" width="310" height="240" />
            <div class="categories font-mono">
                <span>Events</span>
            </div>
            <h3 class="title font-mono">
                <a href="#">Welcome to the New Silent Barn!</a>
            </h3>
            <div class="date font-mono">
                Posted: February 10, 2014
            </div>
            <div class="description">
                Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium
                doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore
                veritatis et quasi architecto beatae vitae dicta sunt explicabo.
            </div>
        </div>
        <div class="block">
            <img src="<?php echo $this->url->get( 'img/block_sample_4.jpg' ); ?>" width="310" height="240" />
            <div class="categories font-mono">
                <span>Press</span>
            </div>
            <h3 class="title font-mono">
                <a href="#">Press and Event Meetings</a>
            </h3>
            <div class="date font-mono">
                Posted: February 3, 2014
            </div>
            <div class="description">
                We need to meet with the Press and Event teams to go over the new site and
                how to use the WordPress blog.
            </div>
        </div>
    </div>
</div>