<!-- Hero/Carousel -->
<div id="hero" class="hero">
    <div id="hero-carousel" class="hero-carousel">
<?php   foreach ( $heroPosts as $heroPost ): ?>
        <div class="slide">
            <img src="<?php echo $heroPost->getImage()->getPath(); ?>" width="960" />
            <div class="blurb">
                <div class="clearfix">
                    <h1>
                        <span><?php echo $heroPost->title; ?></span>
                    </h1>
                </div>
<?php       if ( valid( $heroPost->excerpt, STRING ) ): ?>
                <div class="clearfix">
                    <p><?php echo $heroPost->excerpt; ?></p>
                </div>
<?php       endif; ?>
            </div>
            <a href="<?php echo $heroPost->getPath(); ?>" class="link-overlay"></a>
        </div>
<?php   endforeach; ?>
    </div>
    <div id="hero-nav" class="clearfix">
        <a href="javascript:;" id="carousel-next" class="transition-bg">&rarr;</a>
        <a href="javascript:;" id="carousel-prev" class="transition-bg">&larr;</a>
    </div>
</div>

<!-- Vignettes -->
<div id="vignettes">
<?php   $boxCount = count( $boxPosts );
        for ( $boxIter = 1; $boxIter <= 6; $boxIter++ ): //$boxPosts as $boxPost ):
            if ( ( $boxIter - 1 ) % 3 == 0 ): ?>
    <div class="row clearfix">
<?php       endif;
            // heptagon is placed in spot 6
            if ( $boxIter > 5 ): ?>

        <div class="block clearfix heptagon">
            <img src="<?php echo $this->url->get( 'img/heptagon_yellow.png' ); ?>" alt="Heptagon" />
        </div>

<?php       // pad blank boxes
            elseif ( $boxIter > $boxCount && $boxIter <= 5 ): ?>

        <div class="block">&nbsp;</div>

<?php       else:
                $boxPost = $boxPosts[ $boxIter - 1 ]; ?>

        <div class="block">
            <div class="img-wrap margin-bottom-10">
                <a href="<?php echo $boxPost->getPath(); ?>">
                    <img src="<?php echo $boxPost->getImage()->getPath( 310 ); ?>" />
                </a>
            </div>
            <div class="categories font-mono">
                <span><?php echo map( $boxPost->getCategories()->toArray(), 'name', TRUE ); ?></span>
            </div>
            <h3 class="title font-mono">
                <a href="<?php echo $boxPost->getPath(); ?>"><?php echo $boxPost->title; ?></a>
            </h3>
            <div class="date font-mono">
                Posted: <?php echo date_str( $boxPost->post_date, DATE_DAY_NAME ); ?>
            </div>
            <div class="description">
                <?php echo $boxPost->excerpt; ?>
            </div>
        </div><!-- /block -->

<?php       endif;
            if ( ( $boxIter - 1 ) % 3 == 2 ): ?>
    </div><!-- /row -->
<?php       endif;
        endfor; ?>
</div><!-- /vignettes -->