<!-- Hero/Carousel -->
<div id="hero" class="hero">
    <div id="hero-carousel" class="hero-carousel">
    <?php
    foreach ( $slider as $postId ):
        if ( $sliderPost = get( $posts, $postId ) ): ?>
        <div class="slide">
            <img src="<?php echo $sliderPost->getImage()->getImagePath(); ?>" />
            <div class="blurb">
                <div class="clearfix">
                    <h1>
                        <span><?php echo ( strlen( $sliderPost->title ) > 96 ) ? substr( $sliderPost->title, 0, 96 ) . "&hellip;" : $sliderPost->title; ?></span>
                    </h1>
                </div>
            <?php
            if ( valid( $sliderPost->excerpt, STRING ) ): ?>
                <div class="clearfix">
                    <p><?php echo $sliderPost->excerpt; ?></p>
                </div>
            <?php
            endif; ?>
            </div>
            <a href="<?php echo $sliderPost->getPath(); ?>" class="link-overlay"></a>
        </div>
        <?php
        endif;
    endforeach; ?>
    </div>
    <div id="hero-nav" class="clearfix">
        <a href="javascript:;" id="carousel-next" class="transition-bg">&rarr;</a>
        <a href="javascript:;" id="carousel-prev" class="transition-bg">&larr;</a>
    </div>
</div>

<!-- Vignettes -->
<div id="vignettes">
    <!-- Mobile header -->
    <h3 class="lead centered-text margin-bottom-10 font-mono uppercase" style="display:none;">
        Upcoming @ Silent Barn
    </h3>

<?php
$boxIter = 1;

foreach ( $boxes as $category => $postId ):
    if ( $boxIter === 1 || $boxIter === 4 ): ?>
<div class="row clearfix">
    <?php
    endif;

    $boxPost = get( $posts, $postId );

    if ( ! $boxPost ): ?>
        <div class="block">&nbsp;</div>
    <?php
    else: ?>
        <div class="block">
            <div class="img-wrap margin-bottom-10">
                <a href="<?php echo $boxPost->getPath(); ?>">
                    <img src="<?php echo $boxPost->getImage()->getImagePath( 310 ); ?>" />
                </a>
            </div>
            <div class="categories font-mono">
                <span><?php echo map( $boxPost->getCategories()->toArray(), 'name', TRUE ); ?></span>
            </div>
            <h3 class="title uppercase font-mono">
                <a href="<?php echo $boxPost->getPath(); ?>"><?php echo $boxPost->title; ?></a>
            </h3>
            <div class="date font-mono">
                <!-- Posted: <?php echo date_str( $boxPost->post_date, DATE_DAY_NAME ); ?> -->
                <?php echo $boxPost->getShortDate( TRUE, TRUE ); ?>
            </div>
            <div class="description">
            <?php
            if ( valid( $boxPost->excerpt, STRING ) ):
                echo $boxPost->excerpt;
            else:
                $body = strip_tags( $boxPost->getHtmlBody() );
                echo ( strlen( $body ) > 150 ) ? substr( $body, 0, 150 ) . "&hellip;" : $body;
            endif; ?>
            </div>
        </div><!-- /block -->
    <?php
    endif;

    if ( $boxIter === 3 ): ?>
    </div><!-- /row -->
    <?php
    endif;

    $boxIter++;
endforeach; ?>

    <!-- Heptagon -->
        <div class="block clearfix heptagon">
            <img src="<?php echo $this->url->getStatic( 'img/heptagon_yellow.png' ); ?>" alt="Heptagon" />
        </div>
    </div><!-- /row -->
</div><!-- /vignettes -->
