<!-- Booking Page -->
<div class="page booking clearfix">
    <h1 class="margin-bottom-25 font-mono uppercase">Performance Booking</h1>

    <!-- Booking form -->
    <div class="w47p float-left lineheight-24">
        <div class="margin-bottom-20">
            Oh hi
        </div>
        <div class="margin-bottom-20">
            If you're interested in organizing a show at Silent Barn or if you want to perform here,
            email us at
            <a href="mailto:silentbarnbooking@gmail.com">silentbarnbooking@gmail.com</a>.
            Please include any artists that would be on the bill, production information, the proposed
            date range, and any other relevant information.
        </div>
        <div class="margin-bottom-30">
            Please bear in mind that it is usually very difficult for us to field requests from
            individual bands. Most successful submissions happen when a performer/booker organize an
            entire event. 
        </div>
        <div class="margin-bottom-30">
            Unfortunately we cannot respond to everybody. If you haven't heard back, we encourage you
            to contact other spaces such as
            <a href="http://www.sunnyvalebk.com" target="_blank">Sunnyvale</a>,
            <a href="http://www.the-living-gallery.com" target="_blank">Living Gallery</a>, and
            <a href="http://www.cmoneverybody.com" target="_blank">C'mon Everybody</a>.
        </div>
        <div class="margin-bottom-30">
            We ask for all bands and bookers to read our
            <a href="<?php echo $this->url->get( 'about/saferspaces' ); ?>">Safer Spaces Policy</a>.
        </div>

        <fieldset>
            <legend>
                <h2>Performance Booking Inquiry</h2>
            </legend>
            <form action="<?php echo $this->url->get( 'events/bookinginquiry' ); ?>" method="post">
                <div class="margin-bottom-20">
                    <label>Name</label>
                    <input name="name" type="text" value="" class="w90p" placeholder="Your name...">
                </div>
                <div class="margin-bottom-20">
                    <label>Email</label>
                    <input name="email" type="text" value="" class="w90p" placeholder="Email address...">
                </div>
                <div class="margin-bottom-20">
                    <label>Message</label>
                    <textarea name="message" class="font-asap w90p h150px" placeholder="Message..."></textarea>
                </div>
                <div>
                    <input type="submit" value="Submit" class="round fontsize-16 blue button" />
                </div>
            </form>
        </fieldset>
    </div>

    <!-- FAQ -->
    <div class="w47p float-right faq lineheight-20">
        <div class="margin-bottom-20">
            To help save time and confusion for the both of us, here are a few FAQs:
        </div>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                Who reads these emails? How do you decide who gets to play?
            </dt>
            <dd>
                <span>A:</span>
                Our Calendar Team, a group of 3 curators / admins read submissions and pick events
                on the basis of serving our volunteer body, supporting a wide variety of scenes and
                disciplines, meeting the financial needs of the space, and prolly their own personal
                obsessions, tbh.
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                Does Silent Barn pay performers?
            </dt>
            <dd>
                <span>A:</span>
                Yes!! We charge a cover at events (typically $8 to $10) and give artists 75% of the door
                cut. 25% goes to pay staff and house expenses, with a house minimum. Alternate cuts can be
                negotiated, especially in the case of touring bands or fundraisers. In 2013 we paid over
                $75,000 to performers. Because staff, electricity and space costs money, we are rarely able
                to put on free events at night. If you would like to do a free event, consider proposing it
                between the hours of 4pm and 9pm!
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                What backline gear do you have?
            </dt>
            <dd>
                <span>A:</span>
                Check our
                <a href="https://docs.google.com/document/d/1mj38f0ykdyZW7ExIzoi8QegAvtLpXuqr-KrtV4jRnqY/edit?usp=sharing" target="_blank">backline list</a>.
                We provide a sound person for every event. We do not have CDJs :\ 
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                Do we get a soundcheck?
            </dt>
            <dd>
                <span>A:</span>
                Please let us know ahead of time if you need an extended soundcheck or have specific tech
                needs (including use of our projector), that way we can request that our sound person arrives
                earlier. Otherwise, all acts can do a line check when the sound person arrives, generally an
                hour before doors open.
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                Can we bring food/drinks?
            </dt>
            <dd>
                <span>A:</span>
                There is strictly no BYOB/outside alcoholic beverages allowed at Silent Barn. Because we are a
                licensed food service establishment, event organizers are not permitted to serve outside food
                to the patrons of an event without consent of Silent Barn. Food vendors will also need prior
                approval. You can always bring in outside food for yourself and/or friends!
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                What kind of PR do you do for shows?
            </dt>
            <dd>
                <span>A:</span>
                All basic promo includes a website listing and inclusion in our bi-weekly newsletter + social
                media. Bands/bookers are equally responsible for shows promo (we can't do it alone)! We do not
                currently print flyers ourselves but are happy to post and distribute anything you print and
                drop off to the space.
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                Is Silent Barn accessible?
            <dd>
                <span>A:</span>
                The Main Room of Silent Barn where most shows take place can be entered on level ground that
                is accessible to people using wheelchairs, and the room itself has level ground in the audience
                areas. Please read our
                <a href="https://docs.google.com/document/d/1zwiRUI-LspqRn0d18ygIPFx9bzMiMU1sSpLfCt4P9AQ/edit"
                    target="_blank">full accessibility statement</a> for more information.
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                What are your hours of operation?
            </dt>
            <dd>
                <span>A:</span>
                The space is typically open from 4pm  &ndash; 1am on weekdays. Hours vary on the weekends,
                though we often have daytime programming on the weekends. Most shows are from 8pm  &ndash;
                12am, but we love to do "happy hour" events such as readings and panels, daytime events
                on the weekends, and late nights on Fridays and Saturdays. We try to keep the space active
                as much as possible while respecting our neighbors and residents.
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                Can I visit the space to see it and talk to somebody from the space?
            </dt>
            <dd>
                <span>A:</span>
                Stop by any afternoon between 4 and 8 to check out the space and talk to one of our admin
                staff. Or, to see the space in action, stop by most any night after 8pm (check our calendar
                to make sure we're open) &mdash; let the door person know you'd like to talk to the host
                and we'll often be able to give a walk-through and chat.
            </dd>
        </div>
    </div>
</div><!-- /page -->
