<!-- Booking Page -->
<div class="page booking clearfix">
    <h1 class="margin-bottom-25 font-mono uppercase">Performance Booking</h1>

    <!-- Booking form -->
    <div class="w47p float-left lineheight-24">
        <div class="margin-bottom-20">
            Oh hi
        </div>
        <div class="margin-bottom-20">
            If you're interested in organizing a show at Silent Barn or if you want to perform here,
            send us a message using the form below.
        </div>
        <div class="margin-bottom-30">
            Please bear in mind that we are all volunteers here &mdash; it is usually very difficult
            for us to field requests from individual bands. Most successful submissions happen when a
            performer/booker organize an entire evening.
        </div>
        <div class="margin-bottom-30">
            Unfortunately we cannot respond to everybody. If you haven’t heard back, we encourage you
            to contact other spaces such as Shea Stadium, Palisades Aviv, C’mon Everybody, and Cake Shop.
            We ask for all bands and bookers to read our Safer Spaces Policy.
        </div>
        <div class="margin-bottom-30">
            We ask for all bands and bookers to read our
            <a href="<?php echo $this->url->get( 'about/saferspaces' ); ?>">Safer Spaces Policy</a>.
        </div>
        <fieldset>
            <legend>
                <h2>Performance Booking Inquiry</h2>
            </legend>
            <form action="<?php echo $this->url->get( 'events/bookinginquiry' ); ?>" method="post">
                <div class="margin-bottom-20">
                    <label>Name</label>
                    <input name="name" type="text" value="" class="w90p" placeholder="Your name...">
                </div>
                <div class="margin-bottom-20">
                    <label>Email</label>
                    <input name="email" type="text" value="" class="w90p" placeholder="Email address...">
                </div>
                <div class="margin-bottom-20">
                    <label>Message</label>
                    <textarea name="message" class="font-asap w90p h150px" placeholder="Message..."></textarea>
                </div>
                <div>
                    <input type="submit" value="Submit" class="round fontsize-16 blue button" />
                </div>
            </form>
        </fieldset>
    </div>

    <!-- FAQ -->
    <div class="w47p float-right faq lineheight-20">
        <div class="margin-bottom-20">
            To help save time and confusion for the both of us, here are a few FAQs:
        </div>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                Who reads these emails? How do you decide who gets to play?
            </dt>
            <dd>
                <span>A:</span>
                Our Calendar Team, a group of ~3 volunteer (curators / admins) read submissions and
                vote on every event that goes onto the calendar. They pick events on the basis of
                serving our volunteer body, supporting a wide varieties of scenes and disciplines,
                meeting the financial needs of the space, and prolly their own personal obsessions,
                tbh. Our entire shows team has over a dozen members!
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                Does Silent Barn pay performers?
            </dt>
            <dd>
                <span>A:</span>
                Yes!! We charge a cover at events (typically $7-$10) and give artists 75% of the door cut.
                25% goes to pay staff and house expenses. Alternate cuts can be negotiated, especially in
                the case of touring bands or fundraisers. In 2013 we paid over $75,000 to performers.
                Because staff, electricity and space cost money, we are rarely able to put on free events
                at night. If you would like to do a free event, consider proposing it between the hours of
                4 and 9!.
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                What backline gear do you have?
            </dt>
            <dd>
                <span>A:</span>
                Check our
                <a href="https://docs.google.com/document/d/1mj38f0ykdyZW7ExIzoi8QegAvtLpXuqr-KrtV4jRnqY/edit?usp=sharing" target="_blank">backline list</a>.
                We provide a sound person for every event.
            </dd>
        </dl>
            <dt>
                <span>Q:</span>
                What are your hours of operation?
            </dt>
            <dd>
                <span>A:</span>
                The space is typically open from 4 &ndash; 1 on weekdays. Hours vary on the weekends, though
                we often have daytime programming on the weekends. Most shows are from 8-12, but we love to
                do "happy hour" events such as readings and panels, daytime events on the weekends, and late
                nights on Fridays and Saturdays. We try to keep the space active as much as possible while
                respecting our neighbors and residents.
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                Can I visit the space to see it and talk to somebody from the space?
            </dt>
            <dd>
                <span>A:</span>
                Stop by any afternoon between 4 and 8 to check out the space and talk to a cafe employee!
                Or, to see the space in action, stop by most any night after 8pm (check our calendar to
                make sure we're open) &mdash; let the door person know you'd like to talk to talk to the host
                and we'll often be able to show you through and chat.
            </dd>
        </div>
    </div>
</div><!-- /page -->
