<!-- Booking Page -->
<div class="page clearfix">
    <h1 class="margin-bottom-25 font-mono uppercase">Performance Booking</h1>

    <!-- Booking form -->
    <div class="w47p float-left lineheight-24">
        <div class="margin-bottom-20">
            Oh hi
        </div>
        <div class="margin-bottom-20">
            If you're interested in organizing a show at Silent Barn or if you want to perform here,
            send us a message here.
        </div>
        <div class="margin-bottom-30">
            Please bear in mind that we are all volunteers here - it is usually very difficult for us
            to field requests from individual bands. Most successful submissions happen when a
            performer/booker organizes an entire evening.
        </div>
        <fieldset>
            <legend>
                <h2>Performance Booking Inquiry</h2>
            </legend>
            <form action="<?php echo $this->url->get( 'events/bookinginquiry' ); ?>" method="post">
                <div class="margin-bottom-20">
                    <label>Name</label>
                    <input name="name" type="text" value="" class="w90p" placeholder="Your name...">
                </div>
                <div class="margin-bottom-20">
                    <label>Email</label>
                    <input name="email" type="text" value="" class="w90p" placeholder="Email address...">
                </div>
                <div class="margin-bottom-20">
                    <label>Message</label>
                    <textarea name="message" class="font-asap w90p h150px" placeholder="Message..."></textarea>
                </div>
                <div>
                    <input type="submit" value="Submit" class="round fontsize-16 blue button" />
                </div>
            </form>
        </fieldset>
    </div>

    <!-- FAQ -->
    <div class="w47p float-right faq lineheight-20">
        <div class="margin-bottom-20">
            To help save time and confusion for the both of us, here are a few FAQs:
        </div>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                Who reads these emails? How do you decide who gets to play?
            </dt>
            <dd>
                <span>A:</span>
                A group of ~4 residents at Silent Barn read submissions. If we want to host an event
                submission, then we submit a request to the calendar team. Our "calendar team", which
                votes on every event that goes onto the calendar, consists of 6 volunteers. They pick
                events on the basis of serving our volunteer body, supporting a wide varieties of scenes
                and disciplines, meeting our financial needs, and prolly their own personal obsessions,
                tbh. Our entire shows team has over twenty members!
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                Does Silent Barn pay performers?
            </dt>
            <dd>
                <span>A:</span>
                Yes!! We charge a cover at events (typically $7-$10) and give artists 75% of the door
                cut. 25% goes to pay staff and house expenses. In 2013 we paid over $75,000 to performers.
                Because staff, electricity and space cost money, we are rarely able to put on free events.
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                What backline gear do you have?
            </dt>
            <dd>
                <span>A:</span>
                Check our backline list. We provide a sound person for every event.
            </dd>
        </dl>
            <dt>
                <span>Q:</span>
                What are your hours of operation?
            </dt>
            <dd>
                <span>A:</span>
                Our "normal" show hours are 8-12. But we love to do daytime events, especially on
                the weekends! We don't do super late parties into the night, we ain't no rave den.
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                Can I visit the space to see it and talk to somebody from the space?
            </dt>
            <dd>
                <span>A:</span>
                We're all volunteers, so we're usually away during the day at work. But you can stop
                by most any night after 8pm (check our calendar to make sure we're open) &ndash; let the door
                person know you'd like to talk to talk to the host and we'll often be able to show you
                through and chat.
            </dd>
        </div>
    </div>
</div><!-- /page -->
