<!-- Chefs Page -->
<div id="page" class="page clearfix">
    <h1 class="margin-bottom-25 font-mono uppercase">Community</h1>
    
    <!-- Members list -->
    <div id="members" class="clearfix">
<?php   if ( ! count( $members ) ): ?>

        <div class="color-aaa">
            There are no active members :(
        </div>

<?php   else:
            $i = 1;
            foreach ( $members as $member ):
                $image = ( valid( $member->image_filename, STRING ) )
                    ? $member->getImagePath()
                    : $this->url->get( 'img/heptagon_placeholder_231.png' ); ?>

        <div class="member float-left transition-all" data-index="<?php echo $i++; ?>">
            <div class="img-wrap">
                <img src="<?php echo $image; ?>" />
                <h3 class="name"><?php echo $member->name; ?></h3>
            </div>
            <div class="more-info" style="display:none;">
                <div class="bio"><?php echo trim( $member->bio ); ?></div>
            </div>
        </div>

<?php           if ( $i >= 5 ):
                    $i = 1;
                endif;
            endforeach;
        endif; ?>
    </div>

    <!-- Callout -->
    <div id="member-overlay"></div>
    <div id="member-callout">
        <div class="name"></div>
        <div class="bio"></div>
    </div>
</div>
