<!-- Chefs Page -->
<div id="page" class="page clearfix">
    <h1 class="margin-bottom-25 font-mono uppercase">Chefs</h1>

    <div class="margin-bottom-15 lineheight-24">
        Silent Barn is cooperatively directed by over 70 volunteers. We call ourselves "chefs" and
        really use too many cooking metaphors to describe "The Kitchen", our volunteer
        community<span>&hellip;[<a href="javascript:;" class="show-more" data-target="#chefs-more">read more</a>]</span>
    </div>
    <div id="chefs-more" style="display:none;">
        <div class="margin-bottom-25 lineheight-24">
            Chefs run our events calendar. Chefs fix our sinks. Chefs run our meetings (...we have a
            lot of those). Chefs manage our insurance policies and process our accounting. Chefs
            write our grants and lead fundraising. Chefs live at Silent Barn and create in stewdios
            at Silent Barn. Chefs built this website.
        </div>
        <div class="margin-bottom-25 lineheight-24">
            Chefs at Silent Barn report their work to the group at large, and make decisions together.
            There is no hierarchy here. Is it crazy to run such a huge project without a "boss"?
            Definitely. But we do it anyway, and we think there's something important about a community
            struggling and learning together.
        </div>
    </div>
    <div class="margin-bottom-30 lineheight-24">
        <strong>Here are some of the Chefs that make Silent Barn possible.</strong>
    </div>

    <!-- Members list -->
    <div id="members" class="clearfix">
<?php   if ( ! count( $members ) ): ?>

        <div class="color-aaa">
            There are no active members :(
        </div>

<?php   else:
            $i = 1;
            foreach ( $members as $member ):
                $image = ( valid( $member->image_filename, STRING ) )
                    ? $member->getImagePath()
                    : $this->url->get( 'img/heptagon_placeholder_231.png' ); ?>

        <div class="member float-left transition-all" data-index="<?php echo $i++; ?>">
            <div class="img-wrap">
                <img src="<?php echo $image; ?>" />
                <h3 class="name"><?php echo $member->name; ?></h3>
            </div>
            <div class="more-info" style="display:none;">
                <div class="bio"><?php echo $member->getHtmlBio(); ?></div>
            </div>
        </div>

<?php           if ( $i > 5 ):
                    $i = 1;
                endif;
            endforeach;
        endif; ?>
    </div>

    <!-- Callout -->
    <div id="member-overlay"></div>
    <div id="member-callout">
        <div class="name"></div>
        <div class="bio"></div>
    </div>
</div>
