<!-- Contact Page -->
<div class="page clearfix">
    <h1 class="margin-bottom-25 font-mono uppercase"><?php echo $pageTitle; ?></h1>

    <div class="margin-bottom-15 lineheight-24">
        Silent Barn is a cooperatively run hub of over 70 "chefs", our committed volunteers.
        We divide ourselves up into working groups to swarm around kinds of tasks. Depending
        on what you'd like to do here, here are some different working groups and chefs that
        you might contact. If you're not sure which email is appropriate, just email a random
        address and we can forward you to the right person.
    </div>

    <ul class="margin-bottom-15 lineheight-24">
        <li>
            For <strong>general inquiries</strong>, or to <strong>leave feedback</strong>,
            please email <a href="mailto:helptagon@googlegroups.com">helptagon@googlegroups.com</a>
        </li>
        <li>
            To <strong>book an event or concert</strong>, go to our
            <a href="<?php echo $this->url->get( 'events/booking' ); ?>">event booking page</a>
        </li>
        <li>
            For studio or residential <strong>space rentals</strong> go to our
            <a href="<?php echo $this->url->get( 'about/rentals' ); ?>">rentals page</a>
        </li>
        <li>
            To <strong>rent a stewdio</strong>, go to our
            <a href="<?php echo $this->url->get( 'stewdios/apply' ); ?>">stewdio rentals page</a>
        </li>
        <li>
            For general questions about <strong>stewdios</strong>, email
            <a href="mailto:silentbarnstewdios@googlegroups.com">silentbarnstewdios@googlegroups.com</a>
        </li>
        <li>
            For <strong>press inquiries</strong>, go to our
            <a href="<?php echo $this->url->get( 'about/press' ); ?>">press page</a>
        </li>
        <li>
            To <strong>volunteer</strong> at Silent Barn, go to our
            <a href="<?php echo $this->url->get( 'about/volunteer' ); ?>">volunteering page</a>
        </li>
        <li>
            To contact our <strong>outreach team</strong>, focusing on growing with our neighborhood,
            email
            <a href="mailto:silentbarnispeople@googlegroups.com">silentbarnispeople@googlegroups.com</a>
        </li>
        <li>
            To read our policy on building a <strong>safe and respectful community</strong>, please
            visit our
            <a href="<?php echo $this->url->get( 'about/saferspaces' ); ?>">Safer Spaces Policy</a>
            page; and to contact the Safer Barn working group email
            <a href="mailto:saferbarn@gmail.com">saferbarn@gmail.com</a>.
        </li>
        <li>
            To submit an art project, installation or mural, email
            <a href="mailto:silentbarnpublicart@gmail.com">silentbarnpublicart@gmail.com</a>.
        </li>
    </ul>

    <div class="lineheight-24">
        If you want to talk to us in person, come by an event! Check out
        <a href="<?php echo $this->url->get( 'events/upcoming' ); ?>">our calendar</a>
        to see when we're around.
    </div>
</div>
