<!-- Donate Page -->
<div class="page donate clearfix">
    <h1 class="margin-bottom-25 font-mono uppercase">Donate to the Silent Barn</h1>

    <!-- Intro and video -->
    <div class="block-col clearfix margin-bottom-30">
        <div class="col col-1">
            <blockquote class="clearfix block">
                <i class="fa fa-quote-left"></i>
                <p>An Alt-Arts Mecca</p>
                <cite>&mdash;The New York Times</cite>
            </blockquote>
        </div>
        <div class="col col-2">
            <blockquote class="clearfix block">
                <i class="fa fa-quote-left"></i>
                <p>A 'collective' in the truest sense of the word&hellip; supporting up-and-coming musicians and artists.</p>
                <cite>&mdash;Brooklyn Magazine</cite>
            </blockquote>
        </div>
        <div class="col col-3">
            <blockquote class="clearfix block">
                <i class="fa fa-quote-left"></i>
                <p>They are keeping me, and other independent music lovers like me, alive. I am eternally grateful to them.</p>
                <cite>&mdash;Mitski, Spin Magazine</cite>
            </blockquote>
        </div>
        <div class="col col-4">
            <blockquote class="clearfix block">
                <i class="fa fa-quote-left"></i>
                <p>Best All Ages Club in New York 2014</p>
                <cite>&mdash;Village Voice</cite>
            </blockquote>
        </div>
    </div>

    <!-- 2 column donate links -->
    <div class="margin-bottom-40 clearfix">
        <div class="centered-text padding-all-1p darken-on-hover">
            <div class="padding-bottom-15">
                <h3>Make a tax-deductible contribution!</h3>
            </div>
            <div class="lineheight-24">
                <div class="margin-bottom-25">
                    <a class="fontsize-18 green button submit-paypal" href="javascript:;">
                        <i class="fa fa-heart"></i>
                        Donate Now!
                        <i class="fa fa-heart"></i>
                    </a>
                    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top" style="display:none;">
                        <input type="hidden" name="cmd" value="_s-xclick">
                        <input type="hidden" name="hosted_button_id" value="V3TCPFJM6MZSS">
                    </form>
                </div>
                <div class="fontsize-13 lineheight-18 color-999">
                    Please make it a recurring gift! Contributions of $50 or<br>
                    above are tax-deductible via our non-profit sponsor,<br>
                    Flux Factory. Thank you!
                </div>
            </div>
        </div>
    </div>

    <!-- Thank you -->
    <h2 class="bold margin-bottom-10">
        Thank you!
    </h2>
    <div class="margin-bottom-30 lineheight-24 clearfix darken-on-hover">
        <figure class="w250px float-right padding-all-0 margin-top-0">
            <a class="fontsize-18 blue button margin-bottom-10 inline-blocked" href="<?php echo $this->url->get( 'about/memberships' ); ?>">Become a member!</a>
            <figcaption class="fontsize-13 lineheight-18 color-999">
                Becoming a Member is the best way to help the Silent Barn and the artists who
                live, work, and play here. Join us!
            </figcaption>
        </figure>
        <div class="margin-bottom-25 lineheight-24">
            A donation to Silent Barn is like listener-supported radio. Our galaxy of friends,
            artists, organizers, musicians, art lovers and everyone who has donated and volunteered
            their energy over the past three years has kept Silent Barn alive. Thank you again for
            your support. As ever, we exist for and because of you!
        </div>
    </div>

    <!-- Last year -->
    <h2 class="bold margin-bottom-10">
        Watch the year in 2015
    </h2>
    <div class="margin-bottom-40 lineheight-24 clearfix">
        <iframe width="560" height="315" class="float-right margin-left-30"
            src="https://www.youtube.com/embed/b6Go6Yz3E3E?list=PLFSHcVWOCYEC9OEswWhHB9R8H7Sf4fv69"
            frameborder="0" allowfullscreen></iframe>
        <div class="margin-bottom-15">
            Silent Barn hosts over <strong>400 performances and exhibitions per year</strong>, showcasing
            the work of emerging and established artists, musicians, curators, and educators, and providing
            opportunities to young, local artists. Silent Barn provides <strong>affordable workspace to more
            than 100 artists at a time</strong> where they develop new work and interact with our many
            audiences.
        </div>
        <div>
            We also offer <strong>affordable living spaces to a dozen artists each year</strong> from across
            the United States. In 2015, we averaged over <strong>2,000 guests per month!</strong> 2015 was
            also the year Silent Barn began drafting documents to incorporate as a bona-fide 501(c)3 organization.
        </div>
    </div>

    <!-- 2014 -->
    <h2 class="bold margin-bottom-10">
        Watch the year in 2014
    </h2>
    <div class="margin-bottom-40 lineheight-24 clearfix">
        <iframe width="560" height="315" class="float-right margin-left-30"
            src="https://www.youtube-nocookie.com/embed/videoseries?list=PLFSHcVWOCYEC_7tjZN-1s0YaAqfjT_Sqb"
            frameborder="0" allowfullscreen></iframe>
        <div class="margin-bottom-15">
            Silent Barn hosted <strong>40 shows per month</strong>, attracting <strong>6500 visitors</strong>.
            In addition to hosting shows, Silent Barn is also a community space where the younger and older
            generations can convene and use the space to suit their needs. An example of this is youth
            hip-hop program "Educated Little Monsters" (or "ELM"), who use the space to practice and perform.
        </div>
        <div> 
            Silent Barn is collectively run by <strong>70 volunteer "chefs"</strong> (or department leaders),
            and functions on the generosity and time commitment of donors and volunteers. Silent Barn is also
            home to <strong>15 working groups</strong>, <strong>38 stewdios</strong> and
            <strong>14 artists in residence</strong>. The community has rapidly expanded since Silent Barn's
            inception just under 2 years ago, and continues to expand and improve moving forward.
        </div>
    </div>
</div>