<!-- Donate Page -->
<div class="page donate clearfix">
    <h1 class="margin-bottom-25 font-mono uppercase">Donate to the Silent Barn</h1>

    <!-- Intro and video -->
    <div class="clearfix margin-bottom-30">
        <iframe width="640" height="360"
            class="float-right margin-left-30 margin-bottom-20"
            src="http://www.youtube-nocookie.com/embed/69iW7bLOhIg?rel=0"
            frameborder="0" allowfullscreen></iframe>

        <div class="margin-bottom-25 lineheight-24">
            Silent Barn is a collectively directed art space in Brooklyn, New York. Functioning
            round-the-clock as a center of multidisciplinary experimentation, Silent Barn is a
            place to produce, present, and interact with art of all forms. We are a nonprofit
            organization fiscally sponsored by Flux Factory.
        </div>

        <div class="lineheight-24">
            We are hoping to significantly improve our show experiences, expand our physical space
            for stewdios and artists, and reach out to new audiences with art programs. Our
            audiences are all-ages, from teens to seniors to everyone in between, and we are a
            community space in Bushwick, Brooklyn. Silent Barn’s financial model is based on
            autonomous, multilateral decision-making and curation.
        </div>
    </div>

    <!-- Recent stats and figures -->
    <h2 class="bold margin-bottom-10">
        So far in 2014
    </h2>
    <div class="margin-bottom-40 lineheight-24">
        Silent Barn hosted <strong>40 shows per month</strong>, attracting <strong>6500 visitors</strong>!
        Silent Barn is collectively-run by <strong>70 chefs, 15 working groups, 38 stewdios</strong> and
        <strong>14 artists in residence</strong>. The number of chefs have grown from
        <strong>5 to 70</strong> in just <strong>2 years</strong>!
    </div>

    <!-- 2 column donate links -->
    <h2 class="bold margin-bottom-10">
        Make a Donation
    </h2>
    <div class="margin-bottom-40 clearfix">
        <div class="w47p float-left bg-eee padding-all-1p">
            <h3>Make a tax-deductible contribution!</h3>
            <div class="lineheight-24">
                <div class="margin-bottom-15">
                    <a class="large green button"
                        href="https://www.paypal.com/us/cgi-bin/webscr?cmd=_flow&SESSION=eJBvEz41rA5ZNIB5EBl2gX0h1R6v_oVWYe6R1aoRZ96UzKpr_-105Rm7PjW&dispatch=5885d80a13c0db1f8e263663d3faee8d6cdb53fcfca2b5941339e576d7e42259">
                        <i class="fa fa-dollar"></i>
                        Donate! ($50 or more)
                    </a>
                </div>
                <div>
                    Contributions of $50 or above will be tax-deductible via our non-profit sponsor,
                    Flux Factory. Thank you!
                </div>
            </div>
        </div>
        <div class="w47p float-right bg-eee padding-all-1p">
            <h3>Make a smaller donation!</h3>
            <div class="lineheight-24">
                <div class="margin-bottom-15">
                    <a class="large green button"
                        href="https://www.paypal.com/us/cgi-bin/webscr?cmd=_flow&SESSION=gjFgtJK01Di4_E8M1XVAXOc6EBeeM0gVLmtRE7GljmKaKVhhiXKRsQZM9qG&dispatch=50a222a57771920b6a3d7b606239e4d529b525e0b7e69bf0224adecfb0124e9b61f737ba21b081981b5bc1bed9bcd4a664bb0e309d0a9e4f">
                        <i class="fa fa-dollar"></i>
                        Donate! (less than $50)
                    </a>
                </div>
                <div>
                    Donations of less than $50 can be made directly to the Silent Barn. Every little
                    bit means a lot to this project. Thank you! 
                </div>
            </div>
        </div>
    </div>

    <!-- Thank you -->
    <h2 class="bold margin-bottom-10">
        Thank You!
    </h2>
    <div class="margin-bottom-25 lineheight-24">
        <strong>Silent Barn</strong> was established thanks to the donations of hundreds of
        individuals, and operates through extensive volunteer support. We are so grateful for
        the dedication, support and contributions of everyone involved in the maintenance and
        enhancement of this project.
    </div>
    <div class="margin-bottom-25 lineheight-24">
        Thank you to the <strong>7 Pillar Chefs</strong> of the Silent Barn, without which we
        could not have created this physical space!
    </div>
    <ul class="margin-bottom-25 lineheight-24">
        <li>Joe Ahearn</li>
        <li>Jane Dickson</li>
        <li>Robin Enrico</li>
        <li>“Thurston Moore”</li>
        <li>DRACULA</li>
        <li>Aaron Isaksen</li>
        <li>Tom Swirly</li>
    </ul>
    <div class="margin-bottom-25 lineheight-24">
        A special thank you to our community of supporters and those who gave to the
        <strong>Silent Barn Holiday Fundraiser</strong>!
    </div>
    <div class="margin-bottom-25 lineheight-24">
        “Santa Claus” and 20 anonymous elves, Evans Wohlforth, Kunal Gupta, Drew McDowall,
        Jakob Trollback, Brandon Zwagerman, Brian Brennan, Control Synthesizers &amp;
        Electronic Device, Hillary Livingston, Marina O'Brien, Nicholas Croft, Patty Conway,
        Rachel Petersman, Ryan Walsh, Bob Reich, Ari Zeiguer, Heather Corcoran, Jessi Frick,
        Ad Hoc (adhoc.fm), Sarah Halpern, Stacie Plassche, Joe Plourde, Tristan Perich,
        Haley Duffy, Laura Blosser, Maia Murphy, Lyndsey Albertson, Justin Oren.
    </div>
    <div class="lineheight-24">
        And last but not least, thank you to our <strong>753 supporters</strong> who gave to
        <strong>Rebuilding the Silent Barn Kickstarter</strong>. Without you, the Silent Barn
        would not be possible.
    </div>
</div>