<!-- Gallery Page -->
<div class="page clearfix">
    <h1 class="margin-bottom-25 font-mono uppercase">Barn Art</h1>

    <div class="margin-bottom-15 lineheight-24">
        Silent Barn as a multidisciplinary space hosts visual, installation, and sound art
        throughout the building.
    </div>
    <div class="margin-bottom-30 lineheight-24">
        We call this the public art, or barn art, that describes all art made within the space
        and outdoors that is not in a stewdio or in one of our galleries. Basically bridging
        all public spaces at Silent Barn are murals and art done by artists that submit to the
        barn and create work that can be up for three months to years in the space.
    </div>

    <?php   $this->partial(
            'partials/spaces/blocks', [
                'spaces' => $spaces,
                'noneNoun' => 'galleries'
            ]); ?>
</div>
