<!-- Jobs Page -->
<div class="page jobs clearfix">
    <h1 class="margin-bottom-25 font-mono uppercase">Jobs at The Barn</h1>

    <div class="margin-bottom-25 lineheight-24">
        We're hiring for an Internship positions at the Silent Barn: Sound Engineering Internship.
        Please read below if you're interested in applying!
    </div>

    <!-- 2 columns, once for each listing -->
    <div class="clearfix margin-bottom-40">
        <!-- Operations Coordinator -->
        <div class="float-left border-box padding-right-25 w50p">
            <h2 class="bold margin-bottom-20">
                Sound Engineering Internship
            </h2>

            <table class="table">
                <tr>
                    <th class="lefted-text">Location:</th>
                    <td>Brooklyn, NY</td>
                </tr>
                <tr>
                    <th class="lefted-text">Position Type:</th>
                    <td>Internship</td>
                </tr>
                <tr>
                    <th class="lefted-text">Application Deadline:</th>
                    <td>February 28th, 2018</td>
                </tr>
            </table>

            <h4>Description</h4>

            <div class="margin-bottom-25 lineheight-24">
                Silent Barn is looking for Spring, Fall or Summer interns who are
                interested in learning more about live sound in a constantly evolving
                art space. Interns will get a chance to work with our engineers during
                daily events and assist in setting up events, live mixing and testing
                equipment.
            </div>

            <h4>How to Apply</h4>

            <div class="margin-bottom-25 lineheight-24">
                Please email
                <a href="mailto:intern@silentbarn.org">intern@silentbarn.org</a> with a
                list of relevant experience and a statement of interest. Deadline for our
                Spring internship is February 28th, but we'll accept applicants on a
                rolling basis for Fall &amp; Summer!
            </div>
        </div>
    </div>
</div>

<?php
/*
    <!-- Not hiring -->
    <div class="margin-bottom-25 lineheight-24">
        We're currently not hiring for any positions, but check back often or feel
        free to <a href="<?php echo $this->url->get( 'about/contact' ); ?>">contact us</a>
        to inquire about any openings.
    </div>

    <!-- Hiring -->
    <div class="margin-bottom-25 lineheight-24">
        We're hiring for two new positions at the Silent Barn: Programs Administrator
        and Operations Coordinated. Please read below if you're interested in applying!
    </div>

    <!-- 2 columns, once for each listing -->
    <div class="clearfix margin-bottom-40">
        <!-- Operations Coordinator -->
        <div class="float-left border-box padding-right-25 w50p">
            <h2 class="bold margin-bottom-20">
                Operations Coordinator
            </h2>

            <table class="table">
                <tr>
                    <th class="lefted-text">Location:</th>
                    <td>Brooklyn, NY</td>
                </tr>
                <tr>
                    <th class="lefted-text">Position Level:</th>
                    <td>Experienced (Non-Manager)</td>
                </tr>
                <tr>
                    <th class="lefted-text">Position Type:</th>
                    <td>Part-time</td>
                </tr>
                <tr>
                    <th class="lefted-text">Application Deadline:</th>
                    <td>July 1, 2016</td>
                </tr>
            </table>

            <h4>Description</h4>

            <div class="margin-bottom-25 lineheight-24">
                Silent Barn is hiring an Operations Coordinator to work within the space
                four days a week. This position facilitates all day-to-day operations of
                the organization and acts as the administrative backbone of the collective.
            </div>

            <div class="margin-bottom-25 lineheight-24">
                Responsibilities are wide ranging and include general bookkeeping, payroll,
                permits, invoicing, and purchasing. Other administrative tasks include
                facilitating all utilities and maintenance of the space, acting as a liaison
                to outside vendors and contractors, and contributing to the upkeep of our bar
                to ensure compliance with Health Department standards. The Operations
                Coordinator is also responsible for budget management and basic financial
                reporting. Qualified candidates will have experience in arts administration
                and/or venue operations.
            </div>

            <div class="margin-bottom-25 lineheight-24">
                The Operations Coordinator often acts as the face of the organization, ensuring
                the space opens each day and serving as a point person for general questions and
                conflicts. In addition to overseeing existing tasks, the Coordinator will work
                with the collective to develop and implement new structures and projects for the
                space.The strongest candidates will be flexible, resourceful, and self-motivated
                multi-taskers, tackling issues as they arise while maintaining consistent
                communication with a large group of collaborators.
            </div>

            <div class="margin-bottom-25 lineheight-24">
                Silent Barn is a collectively directed performance venue and artist workspace
                supported by teams of hard-working volunteers. Participating in a collective
                requires listening, patience, and a commitment to transparency. In return, the
                Coordinator will have the opportunity to immerse in a vibrant, supportive
                community of artists, organizers, and youth with a shared dedication to the arts.
                Candidates must be familiar with the Silent Barn ethos, including our mission
                statement, Safer Spaces Policy, and commitment to our communities through
                accessibility and programming.
            </div>

            <h4>How to Apply</h4>

            <div class="margin-bottom-25 lineheight-24">
                The Coordinator will work out of the venue four days a week, with a potential to
                increase hours. Salary will be commensurate with experience. Please submit a cover
                letter and resume, along with any other materials of interest, to
                <a href="mailto:workatsilentbarn@gmail.com?subject=Operations Coordinator [YOUR NAME]">workatsilentbarn@gmail.com</a> with the subject line "Operations Coordinator [YOUR NAME]." For example, "Operations
                Coordinator Seymour Heptagon." Feel free to include links to any creative projects
                in which you participate.
            </div>

            <div class="margin-bottom-25 lineheight-24">
                Due to the expected volume of applications, we unfortunately cannot respond to each
                submission. Candidates selected to move forward will be contacted for an interview the
                first week of July. Silent Barn is an Equal Opportunity Employer.
            </div>

            <div class="margin-bottom-25 lineheight-24">
                <strong>All applications must be submitted by July 1st. Ideal start date will be
                August 1st.</strong>
            </div>
        </div>

        <!-- Programs Administrator -->
        <div class="float-right border-box padding-left-25 w50p">
            <h2 class="bold margin-bottom-20">
                Programs Administrator
            </h2>

            <table class="table">
                <tr>
                    <th class="lefted-text">Location:</th>
                    <td>Brooklyn, NY</td>
                </tr>
                <tr>
                    <th class="lefted-text">Position Level:</th>
                    <td>Experienced (Non-Manager)</td>
                </tr>
                <tr>
                    <th class="lefted-text">Position Type:</th>
                    <td>Part Time Permanent</td>
                </tr>
                <tr>
                    <th class="lefted-text">Application Deadline:</th>
                    <td>July 1, 2016</td>
                </tr>
            </table>

            <h4>Description</h4>

            <div class="margin-bottom-25 lineheight-24">
                Silent Barn is hiring a part-time Programs Administrator to oversee shows-related
                administrative tasks. This role includes various administrative duties that support
                Silent Barn's shows program, such as staffing, bookkeeping, equipment management,
                and other operational tasks.
            </div>

            <div class="margin-bottom-25 lineheight-24">
                The ideal candidate is an experienced performing arts administrator or venue staffer
                with excellent communication skills and a sense of humor. The Administrator works in
                tandem with the existing volunteer Programming Team and Operations Coordinator, assisting
                with day-to-day administration and production, supporting hundreds of events per year.
                The position will begin at 1 to 2 days per week onsite, with the potential to increase
                hours in the future.
            </div>

            <div class="margin-bottom-25 lineheight-24">
                A background in venue management or performing arts administration is preferred, including
                familiarity with live sound. Although booking performances is not part of the Administrator's
                role, an interest is a plus. The strongest candidates will be flexible and resourceful
                multi-taskers, tackling issues as they arise while maintaining consistent communication with
                the collective.
            </div>

            <div class="margin-bottom-25 lineheight-24">
                Silent Barn is a collectively directed performance venue and artist workspace supported
                by teams of hard-working volunteers. Participating in a collective requires listening,
                patience, and a commitment to transparency. In return, the Administrator will have the
                opportunity to immerse in a vibrant, supportive community of artists, organizers and youth
                with a shared dedication to the arts. Candidates must be familiar with the Silent Barn ethos,
                including our mission statement, Safer Spaces Policy, and commitment to our communities
                through accessibility and programming.
            </div>

            <h4>How to Apply</h4>

            <div class="margin-bottom-25 lineheight-24">
                Please submit a cover letter and resume, along with any other materials of interest to
                <a href="mailto:workatsilentbarn@gmail.com?subject=Programs Administrator [YOUR NAME]">workatsilentbarn@gmail.com</a>
                with the subject line "Programs Administrator [YOUR NAME]." For example, "Programs
                Administrator Seymour Heptagon." Feel free to include links to any creative projects
                in which you participate. Due to the expected volume of applications we unfortunately
                cannot respond to each submission. Candidates selected to move forward will be contacted
                for an interview the first week of July. Silent Barn is an Equal Opportunity Employer.
            </div>

            <div class="margin-bottom-25 lineheight-24">
                <strong>All applications must be submitted by July 1st, 2016. Ideal start date will
                be August 1st.</strong>
            </div>
        </div>
    </div>
*/
?>