<!-- Donate Page -->
<div id="memberships" class="page donate clearfix">
    <h1 class="margin-bottom-25 font-mono uppercase">Silent Memberships</h1>

    <!-- 2 column donate links -->
    <div class="position-relative padding-bottom-30 margin-bottom-40 top-shelf cleafix">
        <!-- Intro and picture -->
        <img src="<?php echo $this->url->getStatic( 'img/memberships.jpg' ); ?>" alt="" width="270" />

        <div class="clearfix margin-bottom-10">
            <div class="margin-bottom-25 lineheight-24">
                Becoming a member is the #1 best way to help sustain the Silent Barn collective
                as we build lasting partnerships with our terrific neighbors and collaborators
                and encourage the arts in Bushwick. Silent Membership dollars support artists by
                bringing exciting performers to our intimate venue and commissioning artists to
                improve the space for all showgoers.
            </div>
            <div class="lineheight-24">
                Your support helps fund events with bigger-name acts from around the world and
                produce major projects, including an architect-designed ceiling installation,
                so every show sounds its best. Thank you for helping us make Silent Barn as
                exciting as possible, now and into the future.
            </div>
        </div>

        <h2 class="centered-text bold margin-bottom-15">
            Become a Silent Barn Member
        </h2>
        <div class="centered-text clearfix">
            <a class="green donate donate-submit button margin-right-20" data-target="#paypal-monthly">
                <span>Front Row Membership</span>
                <strong>$25/mo</strong>
            </a>
            <a class="green donate donate-submit button position-relative" data-target="#paypal-onetime">
                <span>Front &amp; Center Membership</span>
                <strong>$300</strong>&nbsp;(one time)
                <em class="note position-absolute">Tax deductable in <?php echo date( "Y" ); ?></em>
            </a>
        </div>
    </div>

    <!-- Two blurbs -->
    <div class="margin-bottom-40 clearfix">
        <div class="w47p float-left bg-eee padding-all-1p">
            <h3>Silent Membership is Easy!</h3>
            <ol class="lineheight-24">
                <li>Make a monthly contribution of $25.00 or more through Paypal.</li>
                <li>Pick up your membership button at the door.</li>
                <li>Enjoy!</li>
            </ol>
        </div>
        <div class="w47p float-right bg-eee padding-all-1p">
            <h3>What are the benefits?</h3>
            <ul class="lineheight-24">
                <li>A glowing heptagon pin, which is your free pass to all of our amazing nightly events</li>
                <li>Exclusive invitation to the "Omni Meeting" where you can meet the entire Silent Barn family and give feedback.</li>
                <li>Playlists from Silent Barn performers.</li>
            </ul>
        </div>
    </div>

    <h2 class="bold margin-bottom-15">
        Frequently Asked Questions
    </h2>
    <div class="faq lineheight-24">
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                Is my gift to Silent Barn tax-deductible?
            </dt>
            <dd>
                <span>A:</span>
                Yes! We are fiscally sponsored by Flux Factory, which manages our not-for-profit
                paperwork. Flux Factory will send you a detailed letter of contribution which you
                can use to tell the IRS you care about DIY culture. Note: If you would like a tax
                deduction for FY 2014, please consider paying the annual membership fee at once.
                Otherwise, you will receive a deduction letter for FY 2015.
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                Who can become a member?
            </dt>
            <dd>
                <span>A:</span>
                At this time, only those who have donated to the Silent Barn in the past have
                access to this offer. It is an exclusive chance to get more involved in our process
                and create a bond.
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                I don’t have Paypal. May I still become a member?
            </dt>
            <dd>
                <span>A:</span>
                We appreciate your dedication! If you do not want a Paypal account, you can make a
                contribution by mailing a check to Flux Factory along with this
                <a href="https://docs.google.com/document/d/1XGIs4EImAeI1xiyHiZyYAhgtu8DgfIfR2FaJ1kTSxiY/edit">membership form</a>.
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                Can I give some other amount?
            </dt>
            <dd>
                <span>A:</span>
                Of course! Every bit helps and we will use 100% of your donation to support Silent
                Membership goals. <a href="javascript:;" class="donate-submit" data-target="#paypal-any">Donate any amount</a>.
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                How do I update, make changes, cancel or suspend my sustaining membership to my
                Silent Membership?
            </dt>
            <dd>
                <span>A:</span>
                Simply send an email to
                <a href="mailto:membership@silentbarn.org">membership@silentbarn.org</a> and we
                will take it from there.
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                I just pledged to give monthly. When will my card be charged?
            </dt>
            <dd>
                <span>A:</span>
                Flux Factory handles all monthly contributions. Accounts are charged on the first
                of the month unless you let us know otherwise.
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                Is Silent Barn a "for profit" company?
            </dt>
            <dd>
                <span>A:</span>
                No. Silent Barn is fiscally sponsored by our friends: Flux Factory. They handle all
                of our not-for-profit administration, while we build a sustainable 501(c)3 model
                that works for the Silent Barn’s mission. We would love your input on this exciting
                conversation.
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                Can I support the barn some other way?
            </dt>
            <dd>
                <span>A:</span>
                Yes! You can be a “Grasshopper” and donate your time.
                <a href="<?php echo $this->url->get( 'barnexam' ); ?>">Take the Barn Exam!</a>
            </dd>
        </dl>
    </div>

    <!-- Paypal forms -->
    <div style="display:none;">
        <form id="paypal-monthly" action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="hosted_button_id" value="DHVA6QLBAUQFU">
            <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
        </form>
        <form id="paypal-onetime" action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="hosted_button_id" value="AVQLHCYFY6YY6">
            <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
        </form>
        <form id="paypal-any" action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="hosted_button_id" value="V3TCPFJM6MZSS">
            <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
        </form>
    </div>
</div>