<!-- Donate Page -->
<div id="memberships" class="page donate clearfix">
    <h1 class="margin-bottom-25 font-mono uppercase">Silent Barn Memberships</h1>

    <!-- 2 column donate links -->
    <div class="position-relative padding-bottom-30 margin-bottom-40 top-shelf cleafix">
        <!-- Intro and picture -->
        <img src="<?php echo $this->url->getStatic( 'img/memberships_3.jpg' ); ?>" alt="" width="270" />

        <div class="clearfix margin-bottom-30">
            <div class="margin-bottom-25 lineheight-24">
                Becoming a Member is the best way to help the Silent Barn and the artists who
                live, work, and play here. Join us!
            </div>
        </div>

        <h2 class="centered-text bold margin-bottom-15">
            Become a Member of Silent Barn
        </h2>
        <div class="centered-text clearfix">
            <a class="green donate donate-submit button margin-right-20" data-target="#paypal-monthly">
                <span>Front Row Membership</span>
                <strong>$25/mo</strong>
            </a>
            <a class="green donate donate-submit button position-relative" data-target="#paypal-onetime">
                <span>Front &amp; Center Membership</span>
                <strong>$300</strong>&nbsp;(one time)
                <em class="note position-absolute">Tax deductible in <?php echo date( "Y" ) + 1; ?></em>
            </a>
        </div>
    </div>

    <!-- Two blurbs -->
    <div class="margin-bottom-40 clearfix">
        <div class="w47p float-left bg-eee padding-all-1p">
            <h3>Silent Membership is Easy!</h3>
            <ol class="lineheight-24">
                <li>Make a monthly contribution of $25.00 or more through Paypal.</li>
                <li>Pick up your membership card at the door.</li>
                <li>Enjoy!</li>
            </ol>
        </div>
        <div class="w47p float-right bg-eee padding-all-1p">
            <h3>What are the benefits?</h3>
            <ul class="lineheight-24">
                <li>A hand-illustrated membership card that is your free pass to all of our nightly events.​</li>
                <li>Exclusive invitation to the "Omni Meeting" where you can meet the entire Silent Barn family and give feedback.</li>
                <li>Playlists from Silent Barn performers.</li>
            </ul>
        </div>
    </div>

    <h2 class="bold margin-bottom-15">
        Frequently Asked Questions
    </h2>
    <div class="faq lineheight-24">
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                Why should I become a member?
            </dt>
            <dd>
                <span>A:</span>
                If you are a frequent visitor, this membership is for you. Pay $25.00 a month
                (What is that? Three coffees? Two movie tickets?) and you’ll get into every show
                for free. You’ll have the added peace of mind that you are contributing to a wide
                community of artists, activists, and community organizers that need your support.
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                Is my gift to Silent Barn tax-deductible?
            </dt>
            <dd>
                <span>A:</span>
                Yes! We are fiscally sponsored by Flux Factory, which manages our not-for-profit
                paperwork. Flux Factory will send you a detailed letter of contribution which you
                can use to tell the IRS you care about DIY culture.
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                Who can become a member?
            </dt>
            <dd>
                <span>A:</span>
                Anyone!
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                Can I become a member for less than a year?
            </dt>
            <dd>
                <span>A:</span>
                We'd prefer a yearly donation so we can all get the most out of our partnership.
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                Does this count for all events?
            </dt>
            <dd>
                <span>A:</span>
                Pretty Much! Except these two things. 1. If the show is sold out, we will be at
                capacity, so get there early. and 2. Title:Point, our favorite theatrical ensemble
                sells tickets to their events because space is so limited. We encourage you to see
                those shows and support their collective when they perform at Silent Barn!
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                I don’t have Paypal. May I still become a member?
            </dt>
            <dd>
                <span>A:</span>
                We appreciate your dedication! If you do not want a Paypal account, you can make a
                contribution by mailing a check to Flux Factory along with this
                <a href="https://docs.google.com/document/d/1ID5axXp1OIjR6pNJC3kqfFe_RlX-wypwWq8f9aLuyNU/edit?usp=sharing">membership form</a>.
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                Can I give some other amount?
            </dt>
            <dd>
                <span>A:</span>
                Of course! Every bit helps and we will use 100% of your donation to support Silent
                Membership goals. <a href="javascript:;" class="donate-submit" data-target="#paypal-any">Donate any amount</a>.
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                How do I update, make changes, cancel or suspend my sustaining membership to my
                Silent Membership?
            </dt>
            <dd>
                <span>A:</span>
                Simply send an email to
                <a href="mailto:membership@silentbarn.org">membership@silentbarn.org</a> and we
                will take it from there.
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                I just pledged to give monthly. When will my card be charged?
            </dt>
            <dd>
                <span>A:</span>
                Flux Factory handles all monthly contributions. Accounts are charged on the first
                of the month unless you let us know otherwise.
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                Is Silent Barn a "for profit" company?
            </dt>
            <dd>
                <span>A:</span>
                No. Silent Barn is fiscally sponsored by our friends: Flux Factory. They handle all
                of our not-for-profit administration, while we build a sustainable 501(c)3 model
                that works for the Silent Barn’s mission. We would love your input on this exciting
                conversation.
            </dd>
        </dl>
        <dl class="margin-bottom-20">
            <dt>
                <span>Q:</span>
                Can I support the barn some other way?
            </dt>
            <dd>
                <span>A:</span>
                Yes! You can volunteer at the next
                <a href="mailto:deepspaceworkinggroup@googlegroups.com">Dirty Hands Club</a> or sign
                up for the <a href="https://helptagon.better.space/">helptagon</a>.
            </dd>
        </dl>
    </div>

    <!-- Paypal forms -->
    <div style="display:none;">
        <form id="paypal-monthly" action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="hosted_button_id" value="DHVA6QLBAUQFU">
            <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
        </form>
        <form id="paypal-onetime" action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="hosted_button_id" value="AVQLHCYFY6YY6">
            <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
        </form>
        <form id="paypal-any" action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="hosted_button_id" value="V3TCPFJM6MZSS">
            <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
        </form>
    </div>
</div>