<!-- Mission Page -->
<div class="page mission clearfix">
    <h1 class="margin-bottom-25 font-mono uppercase">Our Mission</h1>

    <figure class="float-right margin-left-20 margin-bottom-20">
        <img src="<?php echo $this->url->getStatic( 'img/mission-2.jpg' ); ?>" alt="" width="400" />
        <figcaption>
            <div class="margin-bottom-5">
                Public Art Curation:
                <a href="https://instagram.com/color_scenes">@color_scenes</a>,
                <a href="https://www.instagram.com/bushwickstreetart">@bushwickstreetart</a>
            </div>
            <div>
                Photo: Lore Crogan/Brooklyn Daily Eagle
            </div>
        </figcaption>
    </figure>

    <div class="margin-bottom-25 lineheight-24">
        <strong>Silent Barn</strong> is a continually-evolving collective
        based in Brooklyn. We are dedicated to building an open community
        where visitors and members engage with art through all-ages shows
        &amp; events, studio workspace, and education. We also provide space
        for activist groups fighting to empower and protect marginalized people
        outside of our
        walls.
    </div>

    <div class="margin-bottom-25 lineheight-24">
        We value the cooperation of members of all ages, backgrounds,
        experiences, and identities, while prioritizing the safety and comfort
        of those who don't feel at home in other spaces &mdash; notably black
        and brown, native Brooklyn, and LGBTQ communities.
    </div>

    <div class="margin-bottom-25 lineheight-24">
        We work to create an environment that opens dialogue and encourages
        participation from all whose values overlap with ours, whether they've
        been involved for years or hours.
    </div>

    <div class="margin-bottom-25 lineheight-24">
        We unite around the potential of art and education to widen our
        perspectives, uplift the voices of the oppressed, and in turn benefit
        the communities we live in.
    </div>
</div>
