<!-- Mission Page -->
<div class="page mission clearfix">
    <h1 class="margin-bottom-25 font-mono uppercase">Our Mission</h1>

    <img src="<?php echo $this->url->getStatic( 'img/mission.jpg' ); ?>"
        class="float-right margin-left-20 margin-bottom-20" alt="" width="500" />

    <div class="margin-bottom-25 lineheight-24">
        Silent Barn is a collectively directed art space in Brooklyn, New York. Functioning
        round-the-clock as a center of multidisciplinary experimentation, Silent Barn is a
        place to produce, present, and interact with art of all forms.
    </div>

    <div class="margin-bottom-25 lineheight-24">
        In addition to hosting public performances and events, Silent Barn is home to a complex
        of studio and living spaces which serve as an experimental sandbox and public platform
        for a variety of individual artistic, cultural, and entrepreneurial projects. Residents
        live and work amid artistic activity as caretakers of Silent Barn, extending a feeling
        of welcome to audiences and artists.
    </div>

    <div class="margin-bottom-25 lineheight-24">
        Silent Barn is a non-hierarchical organization in which all members are equally empowered;
        it is a social and administrative experiment. Collective curation brings together diverse 
        rtistic practices, creating a climate which uniquely supports accessibility, discovery,
        interaction, and participation. Eclectic programing showcases both emerging and established
        artists, and gives a wide variety of communities the space to form, connect and develop.
    </div>

    <div class="margin-bottom-25 lineheight-24">
        Legalizing the all-ages, DIY ethos enables Silent Barn to engage with the broader public.
        Its financial model disperses sources of support to preserve autonomous, multilateral
        decision-making and curation. Silent Barn exists thanks to the donations of hundreds of
        individuals, and operates through extensive volunteer support.
    </div>
</div>
