<!-- Safer Spaces Policy Page -->
<div class="page saferspaces clearfix">
    <h1 class="margin-bottom-25 font-mono uppercase">Silent Barn Safer Spaces Policy</h1>

    <div class="margin-bottom-25 lineheight-24">
        Please check back soon, we're currently updating this page.
    </div>
    <div class="margin-bottom-25 lineheight-24">
        <small>Last updated: 8 September 2016</small>
    </div>
<?php /*
    <div class="margin-bottom-25 lineheight-24">
        The Silent Barn is a community art space committed to being a safe, respectful
        and positive environment. Silent Barn supports experimental artists by providing
        a space for free expression of all people. We believe that many hierarchical
        structures allow a minority of people to have a voice at the expense of silencing
        others, and that the most interesting, spontaneous, and creative ideas can best be
        realized in spaces where an anti-oppressive policy is nurtured with intention and
        care.  
    </div>

    <div class="margin-bottom-25 lineheight-24">
        In maintaining this ethos, we feel it is important to directly confront social
        hierarchies and oppression as they manifest within our space and at our events.
        We define oppressive behavior as any kind of uninvited physical contact, sexual or
        otherwise, as well as comments or other behaviors that are racist, sexist, homophobic,
        or transphobic, ableist, classist, ageist, or otherwise discriminatory on the basis
        of physical appearance, orientation, gender presentation, ability, or cultural,
        economic, ethnic, national, educational, or religious background. Silent Barn will
        not tolerate language or behavior that is oppressive.
    </div>

    <div class="margin-bottom-25 lineheight-24">
        Individuals who have engaged in oppressive behaviors outside the Silent Barn will
        still be held accountable within it. Those with a history of being called out for
        sexual assault or abuse or other oppressive behaviors may not be permitted entry
        into the space.
    </div>

    <div class="margin-bottom-25 lineheight-24">
        A safe and respectful community is everyone’s responsibility. We encourage you to
        make friends and look out for each other. If you see someone who might be in trouble,
        don’t hesitate to ask them if they need support.
    </div>

    <div class="margin-bottom-25 lineheight-24">
        The Silent Barn’s Safer Spaces Working Group is committed to upholding this policy.
        Any member of the Silent Barn collective may ask you to leave at any time if your
        behavior makes others uncomfortable. If something or someone is making you feel unsafe
        at the Silent Barn for any reason, please tell a staff person, or write to the working
        group directly at: saferbarn@gmail.com.
    </div>

    <div class="margin-bottom-25 lineheight-24">
        Love,<br>
        The Silent Barn
    </div>

    <div class="margin-bottom-25 lineheight-24">
        <em>a no-mean-players space</em><br>
        <em>"don’t be sleazy, be cool"</em>
    </div>
*/ ?>
</div>
