<!-- Thank You Page -->
<div class="page thankyou clearfix">
    <h1 class="margin-bottom-25 font-mono uppercase">Thank You!</h1>

    <div class="margin-bottom-25 lineheight-24">
        Silent Barn was established thanks to the donations of hundreds of individuals, and
        operates through extensive volunteer support. We are so grateful for the dedication,
        support and contributions of everyone involved in the maintenance and enhancement of
        this project.
    </div>

    <h3 class="bold margin-bottom-10">
        A special thank you to our 2015 members!
    </h3>
    <div class="margin-bottom-25 lineheight-24">
        Eric Wohlforth, Michael DiSanto, Brandon Zwagerman, Nicholas Cummins, Eli Dvorkin,
        Drew Mcdowall, Jackson Randall, Ryan Walsh, James McNally, Brad Kim, Alexander Lau,
        Peter Hung, Brian Abelson, Patrick Leggett, Evan Yankey, Kris Petersen, MP Lockwood,
        Rebecca Richards, and Walter Wlodarczyk.
    </div>

    <h3 class="bold margin-bottom-10">
        Additional thank you to our community of supporters in 2014
    </h2>
    <div class="margin-bottom-25 lineheight-24">
        Kunal Gupta, Ghostly International LLC, Sara G Rex, Eric Du, Young Lee, Phillip Nguyen,
        William F. Ingraham IV, Naomi J. Youngstein.
    </div>

    <h3 class="bold margin-bottom-10">
        Thank you to the 7 Pillar Chefs of the Silent Barn, without which we could not have created this physical space!
    </h2>
    <div class="margin-bottom-25 lineheight-24">
        <ul>
            <li>Joe Ahearn</li>
            <li>Jane Dickson</li>
            <li>Robin Enrico</li>
            <li>"Thurston Moore"</li>
            <li>DRACULA</li>
            <li>Aaron Isaksen</li>
            <li>Tom Swirly</li>
        </ul>
    </div>

    <div class="margin-bottom-25 lineheight-24">
        Sincere appreciation for those who gave to the Silent Barn Holiday Fundraiser in 2013.
    </div>

    <div class="margin-bottom-25 lineheight-24">
        And last but not least, to our 753 supporters who gave to Rebuilding the Silent Barn
        Kickstarter. Without you, the Silent Barn would not be possible.
    </div>

    <div class="margin-bottom-25 lineheight-24">
        Infinite thanks for the creation and maintenance of our website by
        <a href="http://mikegioia.com">Mike Gioia</a>.
    </div>
</div>
