<!-- Volunteer Page -->
<div class="page clearfix">
    <h1 class="margin-bottom-25 font-mono uppercase">Volunteer</h1>
    <div class="margin-bottom-15 lineheight-24">
        If you're interested in volunteering at Silent Barn, join us on Better.Space:
    </div>
    <div class="margin-bottom-25 lineheight-24">
        <a class="button green" href="https://cookbook.better.space/">
            Join us on Better.Space
            <i class="fa fa-long-arrow-right"></i>
        </a>
    </div>
</div>
