
<div id="admin" class="page">
    <!-- Edit form -->
    <form id="edit-form" class="clearfix" action="<?php echo $this->url->get( 'admin/users/save' ); ?>"
        method="post" enctype="multipart/form-data">
        <div style="display:none;">
            <input type="hidden" name="id" value="<?php echo $user->id; ?>" />
        </div>

        <!-- Left col -->
        <div class="left-col float-left">
            <!-- General -->
            <fieldset class="margin-bottom-40">
                <legend>
                    <h2>General</h2>
                </legend>
                <div class="margin-bottom-20">
                    <label>Name</label>
                    <input class="w95p" type="text" name="name" value="<?php echo $user->name; ?>" />
                </div>
                <div class="margin-bottom-20">
                    <label>Email</label>
                    <input class="w95p" type="text" name="email" value="<?php echo $user->email; ?>" />
                </div>
                <div class="margin-bottom-20">
                    <label>New Password</label>
                    <input class="w95p" type="text" name="password" value="" />
                </div>
                <div>
                    <label>Permissions</label>
                    <div class="margin-bottom-5">
                        <input type="checkbox" name="access_users" value="1"
                            <?php echo ( $user->access_users ) ? ' checked="checked"' : ''; ?>
                            <?php echo ( int_eq( $user->id, $this->auth->userId ) ) ? ' disabled' : ''; ?> />
                        <span>Can access Users</span>
                    </div>
                    <div class="margin-bottom-5">
                        <input type="checkbox" name="access_members" value="1"
                            <?php echo ( $user->access_members ) ? ' checked="checked"' : ''; ?> />
                        <span>Can access Members</span>
                    </div>
                    <div class="margin-bottom-5">
                        <input type="checkbox" name="access_press" value="1"
                            <?php echo ( $user->access_press ) ? ' checked="checked"' : ''; ?> />
                        <span>Can access Press</span>
                    </div>
                    <div class="margin-bottom-5">
                        <input type="checkbox" name="access_spaces" value="1"
                            <?php echo ( $user->access_spaces ) ? ' checked="checked"' : ''; ?> />
                        <span>Can access Spaces</span>
                    </div>
                    <div class="margin-bottom-5">
                        <input type="checkbox" name="access_pages" value="1"
                            <?php echo ( $user->access_pages ) ? ' checked="checked"' : ''; ?> />
                        <span>Can access Pages</span>
                    </div>
                    <div class="margin-bottom-5">
                        <input type="checkbox" name="access_homepage" value="1"
                            <?php echo ( $user->access_homepage ) ? ' checked="checked"' : ''; ?> />
                        <span>Can set posts to homepage</span>
                    </div>
                    <div class="margin-bottom-5">
                        <input type="checkbox" name="access_publish" value="1"
                            <?php echo ( $user->access_publish ) ? ' checked="checked"' : ''; ?> />
                        <span>Can publish articles</span>
                    </div>
                </div>
            </fieldset>

            <!-- Article Permissions -->
            <fieldset class="margin-bottom-40">
                <legend>
                    <h2>Article Permissions</h2>
                </legend>
                <div>
                    <label>User can add/edit posts in these categories</label>
                <?php
                foreach ( $categories as $category ): ?>
                    <div class="margin-bottom-5">
                        <input type="checkbox" name="category_access[<?php echo $category->id; ?>]" value="1"
                            <?php echo ( $user->canAccessCategory( $category->id ) ) ? ' checked="checked"' : ''; ?> />
                        <span><?php echo $category->name; ?></span>
                    </div>
                <?php
                endforeach; ?>
                </div>
            </fieldset>
        </div><!-- /left-col -->

        <!-- Right col -->
        <div class="right-col float-right">
        </div><!-- /right-col -->
    </form>

    <!-- Delete -->
    <div class="righted-text padding-top-30 margin-top-30" id="delete-wrapper">
        <a class="fontsize-18 red button" href="javascript:;" id="delete-object">
            Delete User
        </a>
        <a class="fontsize-18 black button" href="<?php echo $this->url->get( "admin/users/delete/{$user->id}" ); ?>"
            id="really-delete-object" style="display:none;">
            Click again to confirm
        </a>
    </div>
</div>
