<!DOCTYPE html>
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Admin -- Silent Barn</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Style Sheets -->
        <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
        <link href="http://fonts.googleapis.com/css?family=Share+Tech+Mono" rel="stylesheet" type="text/css">

<?php   if ( $this->config->app->assetMode === 'production' ): ?>
        <link rel="stylesheet" href="<?php echo $this->url->getStatic( 'css/build.css' ); ?>">
<?php   else: ?>
        <link rel="stylesheet" href="<?php echo $this->url->getStatic( 'css/app.css' ); ?>">
<?php   endif; ?>
    </head>
    <body class="admin">
        <!-- Content -->
        <div id="content">
<?php   $this->partial( 'partials/admin/header' );
        echo $this->getContent();
        $this->partial( 'partials/admin/footer' ); ?>
        </div>

        <!-- JavaScripts -->
<?php   if ( $this->config->app->assetMode === 'production' ): ?>
        <script src="<?php echo $this->url->getStatic( 'js/dist/admin.js' ); ?>"></script>
<?php   else: ?>
        <script src="<?php echo $this->url->getStatic( 'js/jquery.js' ); ?>"></script>
        <script src="<?php echo $this->url->getStatic( 'js/underscore.js' ); ?>"></script>
        <script src="<?php echo $this->url->getStatic( 'js/pikaday.js' ); ?>"></script>
        <script src="<?php echo $this->url->getStatic( 'js/jquery.pikaday.js' ); ?>"></script>
        <script src="<?php echo $this->url->getStatic( 'js/jquery.timepicker.js' ); ?>"></script>
        <script src="<?php echo $this->url->getStatic( 'js/jquery.typeahead.js' ); ?>"></script>
        <script src="<?php echo $this->url->getStatic( 'js/jquery.jcrop.js' ); ?>"></script>
        <script src="<?php echo $this->url->getStatic( 'js/jquery.scrollTo.js' ); ?>"></script>
<?php   endif; ?>
        <script src="<?php echo $this->url->getStatic( 'js/admin.js' ); ?>"></script>
    </body>
</html>