<!DOCTYPE html>
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title><?php echo ( isset( $pageTitle ) ) ? $pageTitle.' -- ' : ''; ?>Silent Barn</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Style Sheets -->
        <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
        <link href="http://fonts.googleapis.com/css?family=Share+Tech+Mono" rel="stylesheet" type="text/css">
        <link href='http://fonts.googleapis.com/css?family=Asap:400,700,400italic,700italic' rel='stylesheet' type='text/css'>

<?php   if ( $this->config->app->assetMode == 'production' ): ?>
        <link rel="stylesheet" href="<?php echo $this->url->getStatic( 'css/build.css' ); ?>">
<?php   else: ?>
        <link rel="stylesheet" href="<?php echo $this->url->getStatic( 'css/app.css' ); ?>">
<?php   endif; ?>
    </head>
    <body class="main">
        <!-- Content -->
        <div id="content">
<?php   $this->partial( 'partials/header' );
        echo $this->getContent();
        $this->partial( 'partials/footer' ); ?>
        </div>

        <!-- Environment -->
        <script type="text/javascript">
            window.Environment = {
                apiPath: '<?php echo $this->config->paths->baseUri; ?>'
            };
        </script>
        <!-- JavaScripts -->
<?php   if ( $this->config->app->assetMode == 'production' ): ?>
        <script src="<?php echo $this->url->getStatic( 'js/dist/main.js' ); ?>"></script>
<?php   else: ?>
        <!--<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>-->
        <script src="<?php echo $this->url->getStatic( 'js/jquery.js' ); ?>"></script>
        <script src="<?php echo $this->url->getStatic( 'js/jquery.easing-1.3.js' ); ?>"></script>
        <script src="<?php echo $this->url->getStatic( 'js/jquery.filmroll.js' ); ?>"></script>
        <script src="<?php echo $this->url->getStatic( 'js/jquery.scrollTo.js' ); ?>"></script>
        <script src="<?php echo $this->url->getStatic( 'js/moment.js' ); ?>"></script>
        <script src="<?php echo $this->url->getStatic( 'js/underscore.js' ); ?>"></script>
        <script src="<?php echo $this->url->getStatic( 'js/clndr.js' ); ?>"></script>
        <script src="<?php echo $this->url->getStatic( 'js/jquery.modal.js' ); ?>"></script>
<?php   endif; ?>
        <script src="<?php echo $this->url->getStatic( 'js/main.js' ); ?>"></script>
    </body>
</html>