<table class="md" cellpadding="0" cellspacing="0">
    <thead>
        <tr>
            <th>You type:</th>
            <th>You see:</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>*italics*</td>
            <td><em>italics</em></td>
        </tr>
        <tr>
            <td>**bold**</td>
            <td><b>bold</b></td>
        </tr>
        <tr>
            <td>[Title!](http://silentbarn.org)</td>
            <td><a href="http://silentbarn.org">Title!</a></td>
        </tr>
        <tr>
            <td>* item 1<br>* item 2<br>* item 3</td>
            <td>
                <ul>
                    <li>item 1</li>
                    <li>item 2</li>
                    <li>item 3</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>&gt; quoted text</td>
            <td>
                <blockquote>quoted text</blockquote>
            </td>
        </tr>
        <tr>
            <td>~~strikethrough~~</td>
            <td><strike>strikethrough</strike></td>
        </tr>
        <tr>
            <td>super^script</td>
            <td>super<sup>script</sup></td>
        </tr>
    </tbody>
</table>