<h2 class="with-nav">
    <div class="nav-scroller">
        <?php 
        // Articles
        if ( $adminNavPage == 'articles' ): ?>
        <span>Articles</span>
        <?php
        else: ?>
        <a href="<?php echo $this->url->get( 'admin/articles' ); ?>">Articles</a>
        <?php
        endif;

        // Homepage
        if ( $adminNavPage == 'homepage' ): ?>
        <span>Homepage</span>
        <?php
        else: ?>
        <a href="<?php echo $this->url->get( 'admin/homepage' ); ?>">Homepage</a>
        <?php
        endif;

        // Users
        if ( $this->auth->user[ 'access_users' ] ):
            if ( $adminNavPage == 'users' ): ?>
        <span>Users</span>
            <?php
            else: ?>
        <a href="<?php echo $this->url->get( 'admin/users' ); ?>">Users</a>
            <?php
            endif;
        endif;

        // Members
        if ( $this->auth->user[ 'access_members' ] ):
            if ( $adminNavPage == 'members' ): ?>
    <span>Members</span>
            <?php
            else: ?>
    <a href="<?php echo $this->url->get( 'admin/members' ); ?>">Members</a>
            <?php
            endif;
        endif;

        // Press
        if ( $this->auth->user[ 'access_press' ] ):
            if ( $adminNavPage == 'press' ): ?>
    <span>Press</span>
            <?php
            else: ?>
    <a href="<?php echo $this->url->get( 'admin/press' ); ?>">Press</a>
            <?php
            endif;
        endif;

        // Spaces
        if ( $this->auth->user[ 'access_spaces' ] ):
            if ( $adminNavPage == 'spaces' ): ?>
    <span>Spaces</span>
            <?php
            else: ?>
    <a href="<?php echo $this->url->get( 'admin/spaces' ); ?>">Spaces</a>
            <?php
            endif;
        endif;

        // Pages
        if ( $this->auth->user[ 'access_pages' ] ):
            if ( $adminNavPage == 'pages' ): ?>
    <span>Pages</span>
            <?php
            else: ?>
    <a href="<?php echo $this->url->get( 'admin/pages' ); ?>">Pages</a>
            <?php
            endif;
        endif; ?>
    </div>
    <?php 
    if ( FALSE && $adminNavPage == 'articles' ): ?>
    <a class="fontsize-24 filter-link" href="javascript:;">
        <i class="fa fa-filter"></i>
    </a>
    <?php
    endif; ?>
</h2>
