<div class="centered-text padding-top-30 padding-bottom-20">
<?php
foreach ( $pages as $pageNumber => $value ):
    if ( $value === 'current' ): ?>
    <a href="javascript:;" class="page button blue margin-right-5"><?php echo $pageNumber; ?></a>
    <?php
    // These mean we can render the elipses
    elseif ( $value === 'more' || $value === 'less' ): ?>
    <span class="color-aaa margin-right-5">&hellip;</span>
    <?php
    // numeric means we should render that page link
    elseif ( valid( $value, STRING ) ): ?>
    <a href="<?php echo $this->url->get( 'admin/articles?page='. $pageNumber ); ?>"
        class="page button gray margin-right-5"><?php echo $pageNumber; ?></a>
    <?php
    endif;
endforeach; ?>
</div>